### ISSUE TITLE
[1.12.2] Cannot camouflage door controller

### ISSUE THREAD

**Issue by brisingraerowing** [PC-Logix/OpenSecurity#100]
As per title. Right clicking with a block doesn't do anything.

**Comment by EdTheDog** [comment]
xD Ha! Just found this out too and was going to report it! Beat me to it! :P

**Comment by EdTheDog** [comment]
Look... I know this is Impatient but I was wonder are you going to upload this fix to Minecraft curse forge. If not is there A way I can convert a download of this GitHub into a jar file? Altho you just add the commit and might be uploading It now, I just wanted to know. :P 
Edit: Omg it just updated thank you. Some mod authors wait till they fix like 10 bugs to post a new release. Thank you for not being one of them! xD

**Comment by CaitlynMainer** [comment]
For the record, the only delay here, was waiting on curse to approve the download.

**Comment by EdTheDog** [comment]
Well, thanks anyway! Your the best!
