### ISSUE TITLE
Entity Detector not returning co-ordinates 

### ISSUE THREAD

**Issue by EdTheDog** [PC-Logix/OpenSecurity#102]
Was checking out the entity detector in the new patch, 1.0-8 
and made a program to find entities with it. Now, unlike before, it will return the entities and not just players but for both of them, It won't return the coordinates. It does return the type of entity and the distance to it though. Now, this could, most likely not, be because of my coding. I went over it multiple times and tweaked stuff but nothing worked. Anyway here the program:

local d = require("component").os_entdetector
local e = require("event")
local f = "   "
local bla = function(type, adress, name, range, x, y, z)
   print(type..f..adress..f..name..f..tostring(range)..f..tostring(x)..f..tostring(y)..f..tostring(z))
end
e.listen("entityDetect",bla)
d.scanEntities(3)
os.sleep(5)
e.ignore("entityDetect",bla)

**Comment by CaitlynMainer** [comment]
The entity detector was never meant to return X/Y/Z in the event, but I can see why it would be expected.
