### ISSUE TITLE
Crash on load (1.7.10)

### ISSUE THREAD

**Issue by Keyarose** [PC-Logix/OpenSecurity#103]
Crash happens in initialization, looks like the build version number.
OpenSec: 1.7.10-1.0-110
Minecraft: 1.7.10

Log:
[crash-2018-07-20_15.06.05-client.txt](https://github.com/PC-Logix/OpenSecurity/files/2214952/crash-2018-07-20_15.06.05-client.txt)

**Comment by CaitlynMainer** [comment]
I'm unable to test this change right now, but if you could try to load up http://ci.pc-logix.com/job/OpenSecurity-1.7/111/ and see if it starts I'd appreciate it.

**Comment by cheesealmighty** [comment]
Nope, issue persists on the new build as well. 

https://paste.ubuntu.com/p/GyhGQYf6SY/
