### ISSUE TITLE
Probably not a bug but...

### ISSUE THREAD

**Issue by LawsOfScience** [PC-Logix/OpenSecurity#104]
Ok, so I may just be extremely stupid, but for some reason, the alarm will not play a sound in 1.12.2 version 1.0-9 or 1.0-8, even when I manually set the alarm sound and range.

Yes, I am activating the alarm with "component.os_alarm.activate()", yes it says "Success" or "Ok" when I set the range, set the sound, and when I activate/deactivate it, yes all my sound is on (master, music, block, hostile, you name it).

Like I said, I'm probably just an idiot, but I need to be told how I am being an idiot.

EDIT 7/25/2018 10:24 AM: Oh, and my computer sound is on as well.
EDIT 7/25/2018 10:28 AM: OH, and before I forget
OS: macOS 10.13.3
Forge Version: 1.12.2-14.23.4.2729 
OpenSecurity Version: Tried both 1.0-9 and 1.0-8
OpenComputers Version: 1.7.2.67 (should be the latest)
Lemme know if you need any other specs.

**Comment by CaitlynMainer** [comment]
Do you have logs from this?

**Comment by CaitlynMainer** [comment]
Found and fixed.
