### ISSUE TITLE
keypad color

### ISSUE THREAD

**Issue by ZwinkaDink** [PC-Logix/OpenSecurity#105]
i might just be stupid but cant seem to get the color to change on the keypad i used your example

customButtons = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "<", "0", "ok"}
customButtonColor = {"1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "4"}
keypad.setKey(customButtons, customButtonColor)

and no matter what i change the value the color never changes

**Comment by CaitlynMainer** [comment]
What MC version/Open Security build?

**Comment by CaitlynMainer** [comment]
Nevermind, found the issue, will be fixed next build.

**Comment by ZwinkaDink** [comment]
sorry im playing 1.7.10 for now open security was 1.7.10-1.0-113 and how do you have the color code set up
