### ISSUE TITLE
[Bug] Recipes incompatible with default OpenComputers crafting settings

### ISSUE THREAD

**Issue by Techokami** [PC-Logix/OpenSecurity#107]
Minecraft 1.12.2
OpenComputers 1.7.2.67
OpenSecurity 1.0-10

A bunch of blocks in OpenSecurity (namely: Alarm, Data Block, Card Writer, Magnetic Card Reader, and RFID Reader) require using an un-etched circuit board from OpenComputers to craft. However, I am using the default recipe set in OpenComputers, which does NOT have a recipe for the un-etched boards. (It's only in the harder settings, adding extra steps and complexity to the recipes.) As a result, I am unable to craft the listed blocks.

Somewhat related, neither of the security doors can be crafted either, but this is due to them no longer having recipes?

**Comment by CaitlynMainer** [comment]
The recipes should be referencing the 2nd item in this list https://ocdoc.cil.li/item:materials  Is that not part of the default crafting recipes?

RE: the doors, both have recipes registered https://github.com/PC-Logix/OpenSecurity/blob/1.12.2/src/main/java/pcl/opensecurity/common/ContentRegistry.java#L244-L254  I have no idea why they wouldn't work.

**Comment by CaitlynMainer** [comment]
Oh.. I see it's using the wrong board, it's supposed to be the PCB, not the Circuit Board.

**Comment by Techokami** [comment]
Thank you!
