### ISSUE TITLE
No alarm sound

### ISSUE THREAD

**Issue by drzpk** [PC-Logix/OpenSecurity#111]
_Continuation of #110._

> Also just tested the alarm on the latest build on CF and it works properly, if you're getting any errors on the console please open an issue.

That's the only thing that appears in logs when I activate alarm:
```
[main/WARN] [net.minecraft.client.audio.SoundManager]: Unable to play unknown soundEvent: opensecurity:klaxon1
```
Tested on [d7b0577](https://github.com/PC-Logix/OpenSecurity/commit/d7b057773bb338717c80cb98f49ef783ed474a55).

**Comment by CaitlynMainer** [comment]
I still can't reproduce this, can you give me any other information? OS, Java version, Forge etc..?  It works fine for me on the latest CF build, in dev, other users report it's ok.. I've tried it on multiple computers as well.

**Comment by drzpk** [comment]
Turns out that in the normal game everything works fine. Only when the game is started from a development environment, alarm doesn't work, that's why I've made that pull request. But I guess not everything will work properly in development environment. Sorry if I wasted your time.

**Comment by CaitlynMainer** [comment]
It works fine in my IDE, I use Eclipse, not tried it in IntelliJ, or others though.
