### ISSUE TITLE
[Help] Biometrics reader

### ISSUE THREAD

**Issue by makermacher** [PC-Logix/OpenSecurity#112]
I need help with the Biometric Reader. I have no idea what it doe and I can't find any documentation on it.

Thanks in advance

**Comment by ComputerErika** [comment]
The Biometrics Reader sends a signal whenever a player clicks on it. I'm not sure exactly what the signal is called or what data it returns tho.

**Comment by ben-mkiv** [comment]
you can see events with `dmesg`

the event name is `bioReader` and it contains the UUID of the user who used the block

**Comment by ben-mkiv** [comment]
added documentation to the wiki
https://github.com/PC-Logix/OpenSecurity/wiki/BiometricReader
