### ISSUE TITLE
Crash with Modded Minecraft 1.12.2

### ISSUE THREAD

**Issue by ghost** [PC-Logix/OpenSecurity#113]
Crash during startup, possibly due to a change

[crash-2018-08-19_12.16.33-client.txt](https://github.com/PC-Logix/OpenSecurity/files/2300602/crash-2018-08-19_12.16.33-client.txt)

**Comment by CaitlynMainer** [comment]
Update OpenComputers, recipe for the RFIDReader takes a T1 WLAN card, which doesn't exist in OC 1.7.1.43
https://minecraft.curseforge.com/projects/opencomputers/files/2540146
