### ISSUE TITLE
MagReader Event Pull wrong Event Name

### ISSUE THREAD

**Issue by darkman1984** [PC-Logix/OpenSecurity#114]
Hi!

I've set up a MagReader and changed the event name with setEventName to Test1.
Now when i try to pull the Event via event.pull("Test1") and swipe the Card nothing happens.
But if i try to pull the event via event.pull("magData") instead i'll get the trigger.

Whats wrong?

**Comment by CaitlynMainer** [comment]
MC/Mod Version?

**Comment by darkman1984** [comment]
1.12.2
Version 1.0.12

But nevermind. I don't know why and i cannot reproduce it but it now works.
Where i listed the methods there was
setEventName="Test1"
instead of
setEventName=function(String:name):boolean 

after replacing the magreader it works. Don't know how that happens sorry.
But thanks anyway.
