### ISSUE TITLE
RFID Readers not working

### ISSUE THREAD

**Issue by ThePuzzlemaker** [PC-Logix/OpenSecurity#116]
I'm running OpenSecurity on 1.12.2, and the RFID readers are outputting an empty table. I'm not exactly sure why this is happening.

OpenComputers Version: 1.12.2-1.7.2.67
OpenSecurity Version: 1.12.2-1.0-12

**Comment by ben-mkiv** [comment]
you have to write data to your card before. use the cardwriter for that. (also range is actually divided by 2, so if you want to scan a radius of 5 blocks you have to pass 10 as argument to the scan() method, e.g. do `=component.os_rfidreader.scan(10)` on the lua console)

**Comment by ThePuzzlemaker** [comment]
It appears to have been fixed in a later update.
