### ISSUE TITLE
Crash when a security terminal is rendered

### ISSUE THREAD

**Issue by ghost** [PC-Logix/OpenSecurity#117]
---

**Comment by CaitlynMainer** [comment]
Mod/Forge version would be helpful, I've not seen this crash with the security terminal before..  Also a more complete log might help.
https://drive.pc-logix.com/index.php/s/HZFqQDQBaRp8fdL

**Comment by Silver07** [comment]
Minecraft version: 1.12.2
Forge version: 1.12.2-14.23.5.2772
Opensecurity version: MC1.12.2-1.0-12

Full crash log uploaded to pastebin
https://pastebin.com/6T9hbVru

Additional Information:
Java version: jdk/jre 1.8.0_181

Mods of note, considering this crashes during rendering
-Optifine
-Connected Textures Manager
Mods of note, mods that make major changes
-Foamfix (Anarchy)

The crash occurs at line 26 of SecurityTerminalRender.java in method showFoundTerminals
`for(TileEntity te : tes) {`
Modification of the array whilst being accessed
Maybe `te` is being added or removed during the rendering process??

**Comment by ben-mkiv** [comment]
changed the way they get loaded for rendering in the current build (1.12.2-16)
please give that a try and reopen the issue if it persists for you.
