### ISSUE TITLE
Event Subscriber using very high percentage of tick 

### ISSUE THREAD

**Issue by instinxx** [PC-Logix/OpenSecurity#118]
We only just added the mod to the server and have not attempted to use it. The LagGoggles Mod reports the following. 
![image](https://user-images.githubusercontent.com/1753699/49333981-854bbc00-f597-11e8-9be7-241be8f96431.png)

Any way to reduce its utilization?

**Comment by CaitlynMainer** [comment]
Disable the block break listener in the config, note this will a security doors to be broken, and remove the usefulness of the Security Terminals.

**Comment by ben-mkiv** [comment]
@instinxx i've updated the eventHandler if you are using the securityTerminal or doors i would appreciate to get some feedback if everything is working as expected 
https://github.com/ben-mkiv/OpenSecurity/releases/tag/testbuild

**Comment by CaitlynMainer** [comment]
This should now be fixed in build 16 on CurseForge
