### ISSUE TITLE
[1.12.2] Security Door Issues

### ISSUE THREAD

**Issue by CapdinCrando** [PC-Logix/OpenSecurity#120]
So basically, I have found two bugs with the security doors:

1. Whenever any player punches a security door, it immediately breaks, regardless of who owns it.

2. The security door responds to a redstone signal like a regular door. This means that anyone can slap down a lever and get into my base.

Both of these bugs together make the security door 100% pointless. From my research it shows that you have fixed these exact same bugs in earlier versions of Minecraft, but I thought I would report this so that you could add these fixes to the current version.

I am playing with:
Minecraft 1.12.2
Forge 1.12.2-14.23.5.2768
OpenComputers 1.12.2-1.7.3.146
OpenSecurity 1.12.2-1.0-13

**Comment by kayila** [comment]
I've also noted this issue on my server, the only difference from above is that I'm running Forge 1.12.2-14.23.5.2796. Other than that, all versions are the same.

**Comment by CaitlynMainer** [comment]
This is now fixed in build #16 on CurseForge
