### ISSUE TITLE
Important files are missing

### ISSUE THREAD

**Issue by Heaven31415** [PC-Logix/OpenSecurity#125]
Hi, so far I really enjoy tinkering with this mod. Thanks to everyone who was involved in it's creation.

I think it would be nice to add some basic stuff like README, how to start and how to contribute guidelines. Right now you need to figure out everything yourself, which is not a big problem if you have any experience with Java, Forge and gradle. 

I'm not familiar with this ecosystem, but I'm familiar with programming and I had to spend something like an hour to get up and running with development, which really could have been avoided. With proper instructions it wouldn't take longer than few minutes to just jump right into.

I'm eager to help with those files, however your contribution is needed in order to get something complete and valuable.

**Comment by ben-mkiv** [comment]
First of all, nice what you've done on the wiki so far.

I think there are enough places out there which describe how to setup your IDE for Minecraft development, and this project is like almost any other, no special tinkering needed. (Except for the syncGitWiki task for the build, but the official build server does that anyways)

Also there are many pitfalls with Client/Server logic, so if someone wants to contribute anything useful he should be aware of that anyways (and should know how to setup and build a gradle project)

Maybe i didnt get the point of your post and you can elaborate more ;)

**Comment by Heaven31415** [comment]
> I think there are enough places out there which describe how to setup your IDE for Minecraft development, and this project is like almost any other, no special tinkering needed. (Except for the syncGitWiki task for the build, but the official build server does that anyways)

You are correct, but this repository should be self contained. Anybody interested in development or even helping with small details should have every important information available here. 

I'm not asking for anything unordinary. It's a common practice everywhere to document what this project is about and how to use it. People shouldn't need to go elsewhere in order to get basic information about this mod.

> Also there are many pitfalls with Client/Server logic, so if someone wants to contribute anything useful he should be aware of that anyways (and should know how to setup and build a gradle project)

What kind of pitfalls do you refer to? I think I have an idea, but I'm not 100% sure.

If setting up and building gradle project isn't difficult (and I think it isn't) then we really should document how to do that. It will take us a few moments and may save a lot more for anyone else trying to work on the project.

> Maybe i didnt get the point of your post and you can elaborate more ;)

I just want to make this mod more popular and better, it deserves more attention. In my opinion README isn't only about giving basic information to users, it's an advertisement. Right now we are basically telling people that we are too lazy to even write a simple README, which isn't the best possible approach :P

**Comment by ben-mkiv** [comment]
I've added the missing readme file and some basic build instructions, tell me if you are missing any informations.

About the pitfalls... in order to do advanced changes one must be aware of the client/server logic of minecraft, e.g. what can run on client and what has to run on server and how to sync actions. (but even i do fail at this sometimes ;-))

**Comment by Heaven31415** [comment]
> I've added the missing readme file and some basic build instructions, tell me if you are missing any informations.

Nice job, if I see anything missing or worth adding I will just post a PR.
