### ISSUE TITLE
Keypad is always printing to screen

### ISSUE THREAD

**Issue by Heaven31415** [PC-Logix/OpenSecurity#126]
I have found a bug connected to the keypad. 

If you connect a callback to a keypad signal, every time the callback is called information regarding that event will be printed onto your screen.

How to reproduce:

1. Connect keypad to any computer with screen.
2. Run this script on your computer.
```lua
local event = require "event"
local component = require "component"
local keypad = component.os_keypad

local keypadCallback = function(event, address, button, label)
  -- do nothing
end

event.listen("keypad", keypadCallback)

while true do
  os.sleep(1)
end
```
3. Hit anything on your keypad.
4. Message will be printed on your screen, even though your callback does nothing.

![screen](https://user-images.githubusercontent.com/16988850/52045009-ce8e9c80-2543-11e9-8bd5-44365ca4ab20.png)

**Comment by ben-mkiv** [comment]
can't reproduce. you probably had an old eventListener active from previous tries.

you have to unregister them at the end of your script with something like
`event.ignore("keypad", keypadCallback)`

or restart the computer to get rid of them

**Comment by Heaven31415** [comment]
Yeah sorry, I rushed too early to report it :P
