### ISSUE TITLE
Energy perma-crashes world unless mod is removed

### ISSUE THREAD

**Issue by Mekelaina** [PC-Logix/OpenSecurity#128]
Was playing on a lan world in a custom pack and my friend placed an energy turret which crashed the world. I was only able to recover the world by launching again after removing open security. We tried to put it back in and it crashed again when we returned to the area it was placed. 

[Here's](https://pastebin.com/VdzS8yJR) the crashlog

**Comment by ben-mkiv** [comment]
Thanks for your report, fixed that in dev.
You can grab a prebuild here until a official build has been uploaded to curseForge, i'll leave the bug open until its on curseForge
https://github.com/PC-Logix/OpenSecurity/releases/tag/prebuild

**Comment by Mekelaina** [comment]
> 
> 
> Thanks for your report, fixed that in dev.
> You can grab a prebuild here until a official build has been uploaded to curseForge, i'll leave the bug open until its on curseForge
> https://github.com/PC-Logix/OpenSecurity/releases/tag/prebuild

Thank you!

**Comment by ben-mkiv** [comment]
A build with the fix is now available on curseForge/Twitch launcher, too. (OpenSecurity-MC1.12.2-1.0-21)

**Comment by ben-mkiv** [comment]
sadly i've not fixed the real issue of the bug in build21, so i recommend to upgrade to build22 which should fully cover the issue
