### ISSUE TITLE
Broken Energy Turrets in latest curseforge build

### ISSUE THREAD

**Issue by Gregorsharpe** [PC-Logix/OpenSecurity#129]
OpenSecurity-MC1.12.2-1.0-22.jar

I updated to this version hoping to fix a bug where my energy turrets weren't doing any damage, but it looks like something's gone wrong. The turret item doesn't have an icon, turrets can now only be placed on the floor (as opposed to the ceiling) and when attempting to call the fire() method with a powered and armed turret they spit out the following line. 

`nil        pcl.opensecurity.common.entity.EntityEnergyBolt.func_70016_h(DDD)V`

I also tried grabbing the current version of OS from this repository and building it myself, but that .jar had the same problems which is why I'm raising this issue.

*EDIT*
It seems the roller-doors also appear as a flat-black texture rather than the one shown in the wiki. Perhaps the two could be related?

If any additional information is required I'd love to try to help out!

Best regards,

Greg

**Comment by ben-mkiv** [comment]
Hi, i can confirm the problem with the placing on ceilings, ~but not the other issues. Could you post the whole log please?~ nvm was able to reproduce

The rolldoor default is really dark, did you use some dye on the controller to give it another color?

**Comment by ben-mkiv** [comment]
this build should fix your issues with the energy turret
https://github.com/PC-Logix/OpenSecurity/releases/tag/prebuild

**Comment by Gregorsharpe** [comment]
The build you've posted seems to restore the ability to place turrets on the ceiling and fire them, as well as dealing damage to players. Thanks so much for working on it!

The turrets don't seem to damage mobs at all, hostile or otherwise and I have yet to be able to try this on another player. (Though it can certainly kill me!) Is there some intended functionality that I'm not seeing in the documentation?

You're totally correct on the rolldoor texturing, I applied a dye and it showed up like magic. My apologies!

The energy turret icon is still missing from my hotbar and NEI, but it doesn't affect the functionality.

**Comment by ben-mkiv** [comment]
the turret icon missing is something i had before, can you post a list of your mods? as it seems to be related to another mod.

also the turret should damage mobs, are you playing on a server or in singleplayer mode?

**Comment by Gregorsharpe** [comment]
I've attached a text file containing an ls dump of the mods directory, hopefully that has enough information.

[modlist.txt](https://github.com/PC-Logix/OpenSecurity/files/2927009/modlist.txt)

My most recent tests are being done in a single player world, but I'd be happy to propagate the current build over to my server to test it if that would help.

**Comment by ben-mkiv** [comment]
sorry for bumping this without a fix yet, but leaving another modlist which doesnt show energy turret icon
https://pastebin.com/fu26Hzb6

**Comment by ben-mkiv** [comment]
The mod in question for breaking the EnergyTurret renderer seems to be Botania
https://github.com/Vazkii/Botania/issues/2967

But i wasnt able to reproduce the issue with Turrets not damaging Entities.

**Comment by A-UNDERSCORE-D** [comment]
Confirming that the render is broken even for OS' own blocks. This may want to end up in its own issue. (turret is behind the wall on the right near the torch)
![2019-11-22_03 22 28](https://user-images.githubusercontent.com/21071450/69390343-98d7c180-0cd7-11ea-9f41-87f723f1a2e0.png)

**Comment by ben-mkiv** [comment]
yes please open an own issue for this, and describe when this happened and with which version of the mod (and if optifine is installed)

**Comment by ben-mkiv** [comment]
closing this as i was never able to reproduce the issue, if it still bugs on you please reopen it with the lua code that you used
