### ISSUE TITLE
Card Writer does not write EEPROM

### ISSUE THREAD

**Issue by Namelessys** [PC-Logix/OpenSecurity#131]
Hello o/

the card writer returns the error "Wrong item in input slot" when I try to write on an EEPROM.

I use the version "MC1.12.2-1.0-23".

Sincerely: NoName

**Comment by ben-mkiv** [comment]
Did you use the flash() or write() method? because write() is for cards while flash() is for eeproms

**Comment by Namelessys** [comment]
Yea the flash method is working. It wasn't documented in the wiki thats why I tried to write() it.

Have a nice day o/
