### ISSUE TITLE
[Suggestion] Alarm Switch

### ISSUE THREAD

**Issue by SudoerWithAnOpinion** [PC-Logix/OpenSecurity#132]
I'm wondering how hard it would be to add a block, similar to a keypad, that has one large button in the middle, and one or two indicator lights above it. The button would remain pressed until the API calls reset() or (if enabled via the API) shift right click.

This would be used to setup a bunch of alarm trigger switches  that all activate one central alarm and all panels would become "pressed" to indicate the alarm is active.

**Comment by ben-mkiv** [comment]
I'll close this in favor of #29 which i'm currently working on for OCDevices Mod
Those Panels will allow to add Buttons/Text etc. and would allow to make a "alarm switch" within few lines of Lua Code (also they dont require a graphics card to display their content)
