### ISSUE TITLE
Roll door broken in latest release on curseforge

### ISSUE THREAD

**Issue by Multi-Coder-24** [PC-Logix/OpenSecurity#134]
Having major trouble getting the roll door to work in latest release.

Forge version: 1.12.2-14.23.5.2838
Opensecurity version: 1.0-23
Opencomputers version: 1.7.4.153

**Comment by brisingraerowing** [comment]
And what is happening when you use it?

**Comment by Multi-Coder-24** [comment]
Nothing that's the problem I looked into the wiki to see if I made a mistake but to no avail.

**Comment by ben-mkiv** [comment]
can you show your code and a screenshot of the setup please?

**Comment by Multi-Coder-24** [comment]
yes just bare with me a sec

**Comment by Multi-Coder-24** [comment]
well this is a direct copy of my lua code, could you elaborate on what setup is please
[1.txt](https://github.com/PC-Logix/OpenSecurity/files/3254515/1.txt)

**Comment by ben-mkiv** [comment]
how you placed the blocks

**Comment by Multi-Coder-24** [comment]
Just looked at my setup compared to the wiki and looks like I set it up wrong. Man I feel stupid.

**Comment by Multi-Coder-24** [comment]
![2019-06-04_22 36 25](https://user-images.githubusercontent.com/51382988/58915701-7fd35800-8719-11e9-8ff9-a817765e6ea3.png)
![2019-06-04_22 37 05](https://user-images.githubusercontent.com/51382988/58915703-7fd35800-8719-11e9-9c6c-238f7ed3e3c1.png)
![2019-06-04_22 37 29](https://user-images.githubusercontent.com/51382988/58915704-806bee80-8719-11e9-9eea-e92d1b85e8dc.png)
Theese are all the ways I tried To set it up.

**Comment by Multi-Coder-24** [comment]
Slightly altered code it just toggles the door

**Comment by ben-mkiv** [comment]
that setup is wrong. 
you dont have to fill the area with blocks. just the top line has to be rolldoor blocks, and one controller next to them.

**Comment by Multi-Coder-24** [comment]
OK will try that now and report back in a min

**Comment by ben-mkiv** [comment]
![](https://i.imgur.com/1bCtWNX.png)

**Comment by Multi-Coder-24** [comment]
![2019-06-04_22 47 16](https://user-images.githubusercontent.com/51382988/58916201-e0af6000-871a-11e9-8c3f-e47b87352f49.png)
![2019-06-04_22 47 39](https://user-images.githubusercontent.com/51382988/58916205-e311ba00-871a-11e9-86bf-65cb2253ed8c.png)
Still did not work

**Comment by ben-mkiv** [comment]
why did you place stone blocks below it?! xD

**Comment by Multi-Coder-24** [comment]
yes

**Comment by ben-mkiv** [comment]
remove them!

**Comment by Multi-Coder-24** [comment]
![2019-06-04_22 51 01](https://user-images.githubusercontent.com/51382988/58916305-400d7000-871b-11e9-94b5-6a74158c116a.png)

Removed the stone blocks and nothing is happening.
I must say that this is really good at how quick you responded Thanks.

**Comment by ben-mkiv** [comment]
and then replace the rolldoor blocks cause they probably arent aware about the space below. (or use command `require("component").os_rolldoorcontroller.calibrate()`

**Comment by Multi-Coder-24** [comment]
Just tried the calibrate command and still to no avail

**Comment by Multi-Coder-24** [comment]
![2019-06-04_22 59 11](https://user-images.githubusercontent.com/51382988/58916719-62ec5400-871c-11e9-9c00-a25f59fa9f47.png)
This is what just happened

**Comment by ben-mkiv** [comment]
yea, remove all the rolldoor blocks and place them while looking to west or east on your map

**Comment by Multi-Coder-24** [comment]
That did the trick Thanks man. Just a note could you put that in the wiki as I had no idea.

**Comment by ben-mkiv** [comment]
i'm looking forward about making a video of how to set it up

**Comment by Multi-Coder-24** [comment]
Now that is what we need I searched on youtube for ages to find a video but there is none

**Comment by Multi-Coder-24** [comment]
Again Thanks for the support.
