### ISSUE TITLE
[Suggestion] security cameras 

### ISSUE THREAD

**Issue by Multi-Coder-24** [PC-Logix/OpenSecurity#136]
If it can be done could you add cameras that are viewable using a extension card like (eg. AV card) or using the component api (eg. component.os_camera)

**Comment by ben-mkiv** [comment]
wont be added for several reasons.

1.) we cant render such things on opencomputers screens
2.) other mods already have 'cameras' where Computronics Camera kinda acts like the OpenSecurity Entity Detector, and Security Craft adds a camera with its own screen (which might be worth a try, haven't used the mod yet, so no idea how good that works)

**Comment by Multi-Coder-24** [comment]
SecurityCraft has a render issue with cameras breaking in the latest release on curseforge as for computronics have not tried that mod yet will try it now. Thanks for the suggestion
