### ISSUE TITLE
Card Reader [Bug] 

### ISSUE THREAD

**Issue by ghost** [PC-Logix/OpenSecurity#137]
**Describe the bug**

**To Reproduce**
1. click on card writer
2. insert magnetic strip card
3.exit

**Expected behavior**

Error https://pastebin.com/p2937aT3

**Minecraft:**
 - Mod Version OpenSecurity-MC1.12.2-1.0-29.jar
 - Minecraft Version 1.12.2
 - Forge Version  Forge 1.12.2 - 14.23.5.2838

**Additional context**
I'm trying to set up a personal door

**Comment by ben-mkiv** [comment]
Thanks for your report, the issue should be fixed with release 1.0-31
https://www.curseforge.com/minecraft/mc-mods/opensecurity/files/2731215
