### ISSUE TITLE
[Bug] TileEntityCardWriter.java does not accept null value for getCapability facing enum

### ISSUE THREAD

**Issue by CptnCrackbaby** [PC-Logix/OpenSecurity#138]
When placing the card writer while NuclearCraft is installed the game crashes with a null pointer exception. 

Crash log: https://pastebin.com/R0haSNn3

I've checked TileEntityCardWriter.java, and RadiationHelper.java (from NuclearCraft: https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/radiation/RadiationHelper.java) and can see that NuclearCraft calls getCapability with a null EnumFacing, while TileEntityCardWriter.java assumes that this value is not null.

**To Reproduce**
Install NuclearCraft, OpenComputers, and OpenSecurity.
Place a Card Writer

**Expected behavior**
According to the forge documentation the correct behaviour is for getCapability to handle a null EnumFacing as "it can be assumed that the request comes either from within the block, or from some place where the side has no meaning, such as a different dimension."

**Minecraft:**
 - Mod Version: OpenSecurity-MC1.12.2-1.0-31
 - Minecraft Version: 1.12.2
 - Forge Version: forge-14.23.5.2838

If you need more details please let me know.

**Comment by ben-mkiv** [comment]
Thanks for the report, build 32 has a fix for that and is now on curseForge
https://www.curseforge.com/minecraft/mc-mods/opensecurity/files
