### ISSUE TITLE
[Bug] Energy bolt entity lifespan

### ISSUE THREAD

**Issue by drzpk** [PC-Logix/OpenSecurity#139]
I noticed that energy bolt entities don't disappear when they hit an obstacle.

**To Reproduce**
1. Fire a few shots from the energy turret
2. Wait a few minutes (after that time all energy bolt entities should be gone)
3. Scan for entities (see the screenshot below) and realize that energy bolts are still *alive*

**Expected behavior**
Energy bolts should disappear as soon as they hit an obstacle.

**Screenshots / Code Snippet**
![image](https://user-images.githubusercontent.com/27144202/61145906-e72eb580-a4d8-11e9-9343-f9edb1efd102.png)

**Minecraft:**
 - Mod Version: OpenSecurity-MC1.12.2-1.0-31
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.4.2738

**Comment by ben-mkiv** [comment]
thanks for the bug report. 

here's a build which has the issue fixed:
http://ci.pc-logix.com/job/OpenSecurity-1.12/lastSuccessfulBuild/artifact/build/libs/OpenSecurity-MC1.12.2-1.0-34.jar

i'll leave the bug opened until a public release is on curseForge

**Comment by ben-mkiv** [comment]
version 1.0-35 is now on curseForge which includes the fix
