### ISSUE TITLE
[Bug] Invisible Items with Erebus

### ISSUE THREAD

**Issue by Deliphin** [PC-Logix/OpenSecurity#143]
**Describe the bug**
When both Erebus and OpenSecurity are installed, some Erebus items do not render.

**In which environment did the Bug appear?**
Singleplayer

**To Reproduce**
1. Run with Erebus and OpenSecurity both installed. If OpenSecurity is missing, issue does not occur, so this must be some incompatibility.
2. Look at them in JEI. Spawn them in even, they will not be visible.

**Expected behavior**
![image](https://user-images.githubusercontent.com/14265753/66717097-a1b9a700-edab-11e9-985d-b3b4fb3dd925.png)

**Screenshot**
![image](https://user-images.githubusercontent.com/14265753/66716993-8ac68500-edaa-11e9-91df-028a871be226.png)

**Minecraft:**
 - OpenComputers-MC1.12.2-1.7.4.153
 - OpenSecurity-MC1.12.2-1.0-35
 - Erebus-1.0.30
 - Minecraft 1.12.2
 - Forge 14.23.5.2838

**Additional context**
https://github.com/vadis365/TheErebus/issues/745

I'm not sure if this is on Erebus' or OpenSecurity's side, which is why I'm opening this issue.

This is a very strange issue, because these two mods are wildly unrelated. Erebus adds a dimension, and OpenSecurity adds a few blocks.

**Comment by ben-mkiv** [comment]
Thanks for reporting, the issue was in OpenSecurity and is fixed in version 1.0-39 which is on curseForge now.
