### ISSUE TITLE
[Bug] Alarm crashes game!

### ISSUE THREAD

**Issue by manaphoenix** [PC-Logix/OpenSecurity#144]
**Describe the bug**
VanillaFix picked up a crash when inserting an alarm as an upgrade into a robot with a upgrade container.

**In which environment did the Bug appear?**
Singleplayer

**To Reproduce**
Steps I did to produce:
1. Created a single player world
2. Made a t3 robot as shown https://gyazo.com/a6129010fc164fe463fba9eaf733b8bd
3. Installed OpenOS onto the robot (not sure this is related)
4. Inserted an alarm as an upgrade into the robots upgrade container slot (the robot was powered on)

**Expected behavior**
This area seem self explanatory but, for it to not crash lol.

**Screenshots / Code Snippet**
https://paste.dimdev.org/piyavozoda.mccrash

**Minecraft:**
 - Mod Version (OpenComputers-MC1.12.2-1.7.4.153)
 - Mod Version (OpenSecurity 1.12.2-1.0-39)
 - Minecraft Version (Minecraft 1.12)
 - Forge Version (Forge 14.23.5.2847)

**Additional context**
If somehow helps, this was a flat world, set to the redstone ready preset.

**Comment by ben-mkiv** [comment]
kinda fixed locally, but the alarm isn't ideal as upgrade anyways as minecraft doesn't support moving sound sources, so it will always come from the location where the robot/tablet started playing the sound

i'll leave the bug opened until a release is on curseForge

**Comment by ben-mkiv** [comment]
official build with the fix is now on curse

https://www.curseforge.com/minecraft/mc-mods/opensecurity/files/2939430
