### ISSUE TITLE
[Bug] Card writer dosen't write accurate data

### ISSUE THREAD

**Issue by Asmoyed** [PC-Logix/OpenSecurity#146]
**Describe the bug**
Mag card data write dosen't work, I'm trying to write encoded data with the component data from OC, but the data on the does not match the result from the encryption function

**In which environment did the Bug appear?**
Singleplayer

**To Reproduce**
Encrypt a string with OC encrypt function
Write the result onto a mag card
Read the data of the card
Result and card data arent equal

**Expected behavior**
The encrypted data should be properly written onto the card

**Screenshots / Code Snippet**
```lua
component = require("component")
writer = component.os_cardwriter
data = component.data
reader = component.os_magreader
key = data.random(128)
iv = data.random(16)
writer.write(data.encrypt("test",key,iv),"Test Card")
_, _, _, cardData = event.pull("magData")
print(cardData == (data.encrypt("test",key,iv))
```
![image](https://user-images.githubusercontent.com/42284092/67783358-6cc77880-fa6a-11e9-8947-33352dee1e5d.png)

**Minecraft:**
 - Mod Version (e.g. OpenSecurity-MC1.12.2-1.0-35)
 - Minecraft Version : 1.12.2
 - Forge Version : 14.23.5.2847)

**Additional context**
Nothing more to say

**Comment by ben-mkiv** [comment]
The cardwriter writes Strings while the data component probably returns an byte Array. Cant really test it right now as your test script wont work for me at all. 

Could you try to convert the data with `component.data.encode64(data)` before writing it and decoding it after reading with `component.data.decode64(data)` that might work around the issue

**Comment by Asmoyed** [comment]
It seems to be working 
Thanks ^^

**Comment by ben-mkiv** [comment]
added this information to the wiki https://github.com/PC-Logix/OpenSecurity/wiki/CardWriter#binary-data

Closing this as it seems to be resolved.
