### ISSUE TITLE
[BUG] Rolldoor does not appear in 1.7.10

### ISSUE THREAD

**Issue by Xlaits** [PC-Logix/OpenSecurity#148]
The rolldoor and rolldoor controller from the latest curseforge download for 1.7.10 only shows up as a missing texture block, it's name showing up as tile.SecurityDoor.name.

**Comment by ben-mkiv** [comment]
thats the normal security door, the Rolldoor never got ported back to 1.7.10

**Comment by Xlaits** [comment]
Is it at all possible to backport it?

**Comment by ben-mkiv** [comment]
probably, but i'm personally not interested in supporting a 5 years old minecraft version. If you find someone who backports it and makes a pull request, we would include the change in the official OpenSecurity builds.

**Comment by Xlaits** [comment]
Sounds like it's time for me to re-learn some Java.

**Comment by ben-mkiv** [comment]
no, it's time for you to get a more recent minecraft version ;-)

**Comment by Xlaits** [comment]
A majority of the mods I care about never updated past 1.7.10.

**Comment by ben-mkiv** [comment]
ok, then its time to learn java to update those mods ;)

but i'm curious which mods you talk about, some got just new names as they where ported by new devs

**Comment by Xlaits** [comment]
Off the top of my head, Witchery died with it's creator going dark. (Many
people have tried to update it, to various successes, none of them feel
right, though.) ChocoboCraft, I think... Thaumic Horizons and Thaumic
Energistics... and I wish that Thaumcraft 2/3 was still available...

**Comment by ben-mkiv** [comment]
Chococraft: https://www.curseforge.com/minecraft/mc-mods/chococraft-3
Witchery: https://www.curseforge.com/minecraft/mc-mods/bewitchment

But yea, a lot of Thaumcraft stuff is dead since it was closed source...

But still you are missing out some great 1.12 "exclusive" (magic) mods like Astral Sorcery, PSI and probably many more

**Comment by Xlaits** [comment]
I already love the sound of Astral Sorcery. If I can find equivalents of the mods in this pack, I'll probably update it. I just need to yell at the guy who made it, too.
