### ISSUE TITLE
Connect Keypad with Rolldoor

### ISSUE THREAD

**Issue by Alica211** [PC-Logix/OpenSecurity#149]
Hi,

I'm just a beginner, so I need some help to connect my rolldoor with a keypad to open an close it.
![2019-11-16_10 46 49](https://user-images.githubusercontent.com/57828743/68991374-6f91de00-085e-11ea-8da9-ef08a4ccb7ae.png)
 this is what I got till now :)

**Comment by ben-mkiv** [comment]
i've added an example script to the keypad wiki section, that should help you to figure out how to get it done
https://github.com/PC-Logix/OpenSecurity/wiki/Keypad#example-script

**Comment by Alica211** [comment]
thank you :)

**Comment by Alica211** [comment]
could you explain the function updateDisplay() :)

**Comment by ben-mkiv** [comment]
it just generates a string of `*` characters as long as the cached user input is, and displays it on the keypad display

**Comment by Alica211** [comment]
![2019-11-16_15 46 48](https://user-images.githubusercontent.com/57828743/68994962-d1673d80-0888-11ea-9d6b-3a0f340fa09b.png)
 this is what I did, but the display doesn't change at any point :/

**Comment by ben-mkiv** [comment]
because button_label isn't passed to the updateDisplay function.

change the function declaration to 
```lua
function updateDisplay(button_label)
[all the code within the function]
end
```
and change the method call to `updateDisplay(button_label)` (pretty much at the end of your screenshot)

**Comment by Alica211** [comment]
![2019-11-16_16 20 09](https://user-images.githubusercontent.com/57828743/68995342-f958a000-088c-11ea-9fce-27b6fd1d1a28.png)
 changed it but nothing happend 

sorry that I need so much help :O

**Comment by ben-mkiv** [comment]
nvm... the whole function is messed up. you want to display what you typed?

remove the whole updateDisplay function and replace the function call at the end of the screenshot by
`keypad.setDisplay(keypad_input, 7)`

**Comment by Alica211** [comment]
yes and I want to open my rolldoor with the keypad

to remove the function and replace the stuff at the end didn't change anything :/

**Comment by ben-mkiv** [comment]
sorry
`keypad.setDisplay(keypadInput, 7)`

**Comment by Alica211** [comment]
yes, already did it that way but nothing happend

**Comment by ben-mkiv** [comment]
upload the whole script, you can do that on the computer with an internet card and `pastebin put scriptName.lua`

**Comment by Alica211** [comment]
and still nothing happens :(

**Comment by ben-mkiv** [comment]
as said before, you should post the whole script, as i dont know what else you have in there...
