### ISSUE TITLE
[Suggestion]  Turn Down The Keypad Volume.

### ISSUE THREAD

**Issue by Multi-Coder-24** [PC-Logix/OpenSecurity#151]
What I would like is to have the ability to turn down the kaypad volume as currently it's extremely loud and annoying. So basically if you can add a feature such as keypad.setVolume() which accepts a float between 0.0 and 1.0 as to turn down the volume, if this is not possible can you add it into the configs. Many Thanks DDX5.

**Comment by ben-mkiv** [comment]
yes that can be added, you can already turn off the sound with `setShouldBeep(false)`

**Comment by Multi-Coder-24** [comment]
Thanks for the info. This really helps as the sound from the keypad is substantially louder than other sounds.

**Comment by Multi-Coder-24** [comment]
@ben-mkiv @CaitlynMainer Merry Christmas OpenSecurity Team and happy new year

**Comment by ben-mkiv** [comment]
took me almost half a year to add that 10 lines of code... but just uploaded a new build on curse which has the feature to set the volume, e.g.: `component.os_keypad.setVolume(0.4)` 

https://www.curseforge.com/minecraft/mc-mods/opensecurity/files/2939430

**Comment by Multi-Coder-24** [comment]
Thank You Very Much I Do Appreciate The Work You Have Done
