### ISSUE TITLE
how do you make securOS work ???

### ISSUE THREAD

**Issue by attilavs2** [PC-Logix/OpenSecurity#152]
when I try to launch securOS on my computer, it asks me a username and a password and I've tried many but it's not working.
Can someone help me ?

**Comment by ben-mkiv** [comment]
SecureOS wasn't updated in a while, maybe you can get some help here: https://oc.cil.li/topic/655-secureos/

also i would advice to take a look on this, as it seems to be more recent: https://oc.cil.li/topic/994-security-system-for-opensecurity/

I'll leave the bug opened and see if we remove SecureOS if its not working anymore.
