### ISSUE TITLE
data block not showing up in component list? [Bug] 

### ISSUE THREAD

**Issue by misterB0420** [PC-Logix/OpenSecurity#153]
Minecraft 1.12.2, 
opencomputers 1.7.2.67, 
opensecurity v 1.0-39, 
modpack FTB revelation with ichunutil and G.L.A.S.S. mods,

This is most likely due to some conflict somewhere in the modpack but i just wanted to get confirmation, in case i'm just doing something wrong. I have a tier 3 server setup and I'm trying to connect the data block to it using network cable but it doesn't show up in the component list, it doesn't get an address in the tooltip, it doesn't even fire a component_added event when placed. I tried placing an adaptor as well, to no effect.

Edit: playing in single player, and opensecurity is also an aftermarket add in to the pack i'm using.

**Comment by brisingraerowing** [comment]
Did you use the Server Rack GUI to connect the server to a side of the rack?

**Comment by misterB0420** [comment]
yep, sure did. I've got a screen on the same cable working just fine as well

**Comment by brisingraerowing** [comment]
What does the components command list? The data block should create a ‘data’ component.

**Comment by misterB0420** [comment]
yeah, I can get that component with the data card from oc, but it doesn't show up at all with the data block. right clicking the block with the analyzer does absolutely nothing as well, no printout at all. with the data block connected I see this as my component list:
gpu
filesystem
filesystem
keyboard
eeprom
screen
modem
computer

**Comment by ben-mkiv** [comment]
could you provide your minecraft log please? Best would be some log where you just place and remove the data block

**Comment by ben-mkiv** [comment]
also try with a newer opencomputers version please, 1.7.2 is >2 years old

**Comment by ben-mkiv** [comment]
closing due to age

please open a new issue with reference to this one if the problem still exists
