### ISSUE TITLE
Lack of information on OpenSecurity in the masses, specifically we are talking about Rolldor's and rolldorconroller. We need help.

### ISSUE THREAD

**Issue by Snoozeex** [PC-Logix/OpenSecurity#154]
Good afternoon, I can't find the opensecurity mod guide or guide anywhere. I want to understand and install rolldor's, but I can't find any information anywhere. Installed the computer, installed the operating system, installed rolldor controller, rolldor's, and then a dead end. Could you share a link to the literature/guide I need to help me figure it out? On YouTube and all over the Internet, I didn't find any information about rolldor's. And the link to Your discord channel is not up to date, could you give an up-to-date one? On the server where we play with these mods, no one had anything to do, no one understands.

**Comment by ben-mkiv** [comment]
Did you take a look at the Wiki?

https://github.com/PC-Logix/OpenSecurity/wiki/RolldoorController

https://github.com/PC-Logix/OpenSecurity/wiki/Rolldoor

The Discord Channel is on the official OpenComputers Discord
https://discord.gg/H2UyJXe

**Comment by ben-mkiv** [comment]
added a video of how to set it up to the wiki, closing this issue now
[YouTube Video which shows how to setup a rolldoor](https://www.youtube.com/watch?v=ab-SApBGlY4)
