### ISSUE TITLE
[Bug] Crash on world rejoin after using NanoFog Terminal

### ISSUE THREAD

**Issue by zack-emmert** [PC-Logix/OpenSecurity#156]
**Describe the bug**
After using the NanoFog terminal to place a block, rejoining the world causes the game to crash.

Here is the crash log: [https://paste.ee/p/df6N8](https://paste.ee/p/df6N8)

**In which environment did the Bug appear?**
Singleplayer

**To Reproduce**
1. Set up a computer with a NanoFog Terminal
2. Use it to place a NanoFog block
3. Leave the world and rejoin

**Expected behavior**
It should simply not crash and continue to function

**Minecraft:**
 - Mod Version: 1.0-46
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2854
[ x] Optifine installed (if the issue is render related and you use Shaders add informations about what Shader you are using) No shaders

**Comment by ben-mkiv** [comment]
fixed in 1.0-47
