### ISSUE TITLE
[Bug] Alarm setAlarm method returns true if the sound is invalid

### ISSUE THREAD

**Issue by GHXX** [PC-Logix/OpenSecurity#161]
**Describe the bug**
Calling .setAlarm() while passing a sound name that doesnt exist, makes the function return true

**In which environment did the Bug appear?**
Singleplayer, fresh world.

**To Reproduce**
1. Make a new world
2. use the /oc_sc command to plop down a opencomputers computer
3. place an alarm block next to the computer
4. turn on the pc
5. open the lua prompt in oc by typing "lua" and hitting enter
6.1. set the variable "a" to be an alarm (a = require("component").os_alarm)
6.2 now execute `a.setAlarm("wontwork")`
7. observe that the result is `true`

**Expected behavior**
The function should throw a error if the sound is invalid.
Users can use pcall to catch those errors if necessary. Just making it return false is not a good option in my opinion.

**Screenshots / Code Snippet**
If applicable, add the code you used and screenshots of how your setup looks like
![image](https://user-images.githubusercontent.com/5289076/103500025-71e03e80-4e4a-11eb-85eb-1b6e419f984e.png)
![image](https://user-images.githubusercontent.com/5289076/103500028-74db2f00-4e4a-11eb-80be-b93f8fd260d8.png)

**Minecraft:**
 - Mod Version (e.g. OpenSecurity-MC1.12.2-1.0-48)
 - Minecraft Version (e.g. Minecraft 1.12)
 - Forge Version (e.g. Forge 14.23.5.2854)
(some other mods are installed, but this should not be a compatibility issue i am assuming) 
![image](https://user-images.githubusercontent.com/5289076/103499698-4577f280-4e49-11eb-8d75-091ca21e327e.png)

**Additional context**
There are no outputs in the log file while this problem happens.

**Comment by CaitlynMainer** [comment]
This isn't a bug, as setAlarm always returns true. The server never sees the sounds the client has loaded, so it would have no way of knowing if a sound exists or not.
