### ISSUE TITLE
Magnetic card reader help

### ISSUE THREAD

**Issue by ghost** [PC-Logix/OpenSecurity#163]
I've been trying to work out how to use the card reader to print the data on the card on the display, but all I've found is an event. Being an idiot and also a new programmer who has no idea what I'm doing, I can't figure out how to get data out of an event. Any help?

**Comment by Shuudoushi** [comment]
Local thing = tostring (event.pull(<i don't remember exact context, check wiki>))
Print(thing)

Should work

**Comment by ben-mkiv** [comment]
```lua
event = require("event")

function myFunction(eventName, address, playerName, cardData, cardUniqueId, isCardLocked, side)
   print("player " .. playerName .. " used card " .. cardUniqueId .. ", data: " .. cardData)
end

-- subscribe to the event "magData" with myFunction() when a card is used
event.listen("magData", myFunction)

-- wait for an interrupt before closing the script (CTRL + C)
event.pull("interrupted")

-- unsubscribe from the event bus
event.ignore("magData", myFunction)
```

**Comment by big-lip-bob** [comment]
The [Event API](https://ocdoc.cil.li/api:event) might be what you're looking out after then as Ben pointed out, the returned values are (in order) `eventName, address, playerName, cardData, cardUniqueId, isCardLocked, side`

**Comment by ghost** [comment]
Thanks so much. This did the trick.
