### ISSUE TITLE
would you please help me set up the keypad

### ISSUE THREAD

**Issue by honza1231** [PC-Logix/OpenSecurity#164]
I would like to help make a keypad because I can't program

**Comment by MajorGeneralRelativity** [comment]
Fortunately, the mod already comes with one! Enjoy: https://github.com/PC-Logix/OpenSecurity/wiki/Keypad

**Comment by honza1231** [comment]
but I don't understand him

**Comment by big-lip-bob** [comment]
https://www.tutorialspoint.com/lua/index.html
https://ocdoc.cil.li/component:component_access
https://ocdoc.cil.li/api:component

**Comment by honza1231** [comment]
there would be a video that would explain it all

**Comment by big-lip-bob** [comment]
There's no need, the docs explain it very well, as soon as you know OC

**Comment by ben-mkiv** [comment]
if you want some plug and play solution you should stick to another mod, 
SecurityCraft seems to have an Keypad which should be easier to setup for people who don't want to code.

If you have a specific problem with the component you should show your code and tell us where you got stuck or what you don't understand.

The concept of the keypad is pretty easy, each time you press a key a opencomputers event is fired which contains informations, those events can be listened to and what you do with that information is up to you.

also see [https://ocdoc.cil.li/api:event](https://ocdoc.cil.li/api:event) for more informations about events and how to listen to them
