### ISSUE TITLE
[Bug] Entity Detector stops outputting after a few uses

### ISSUE THREAD

**Issue by the-sushi** [PC-Logix/OpenSecurity#165]
**Describe the bug**
This is in a 1.10.2 modpack

Using the Entity Detector about 3 to 5 times outputs fine but after that it stops outputting anything. It still makes a noise after this though, and replacing the block gets it to output again.

I'm not sure if I'm just doing something wrong. It still has stored power 

This is on a forge server hosted by a friend

**Expected behavior**
It keeps outputting information

I'm not going to include any code because its as simple as doing `entdec.scanEntities()` multiple times in interactive lua or doing the same and outputting info in a .lua file.

**Minecraft:**
 - OpenSecurity 1.0-43
 - Minecraft 1.10.2
 - Forge Version 8.0.99.99
[ ] Optifine installed no

**Comment by the-sushi** [comment]
I forgot to mention that I have tested it in creative in singleplayer with the same results and it also doesnt send signals anymore either.

**Comment by LMWafer** [comment]
I have the same exactly issue: detector.scanEntities() returns 2 not empty tables and then stops. detector.scaPlayers() returns the same thing. 
In 1.7.10 modpack running on an aternos server. 
The detector repeats the same thing after reboot. 

**Minecraft:**
- OpenSecurity version : 1.0-117
- Minecraft version : 1.7.10 
- Forge version : 10.13.4.1614
- Optifine installed

**Comment by ben-mkiv** [comment]
both versions didn't receive any bugfixes within the last two years, and the current version is 1.12.2

most likely there won't be a bugfix for 1.7.10 or 1.10.2
