### ISSUE TITLE
[Bug i think] failed contacting mojang api

### ISSUE THREAD

**Issue by LittleTimmy52** [PC-Logix/OpenSecurity#175]
i put getAllowedUsers(password) in a print and when it prints i see failed contacting mojang api, I have addedmyself as a user, but i only see this, do i need to do anything diffrently in my code which is here: 
![Codept1](https://user-images.githubusercontent.com/90333044/193485099-8915a070-9c95-41ee-9b0f-5e72a05da203.JPG)
![Codept2](https://user-images.githubusercontent.com/90333044/193485107-2e9e6d53-6238-4815-903f-4c39780eb258.JPG)

**Comment by LittleTimmy52** [comment]
when i run the code i get this:
![Coderan](https://user-images.githubusercontent.com/90333044/193485214-797d8255-4d43-4918-b20f-543e426e7e1c.JPG)

**Comment by CaitlynMainer** [comment]
@ben-mkiv Do you interact with the Mojang API in the security terminal?

**Comment by CaitlynMainer** [comment]
@LittleTimmy52 are you running in offline mode, or on a pirated copy of the game?

**Comment by LittleTimmy52** [comment]
@CaitlynMainer i am using a reall minecraft, and im connected to my aternos server, so im online

**Comment by CaitlynMainer** [comment]
Check your server log when you try to run the code and see if you get any errors.

**Comment by LittleTimmy52** [comment]
ok ill try that

**Comment by LittleTimmy52** [comment]
@CaitlynMainer this is what i got http://pastie.org/p/4Nzc745d6CEAibsEUhiBD7

**Comment by CaitlynMainer** [comment]
@ben-mkiv  You're using the name history API for the security terminal? That API was disabled Sept 13th.

**Comment by LittleTimmy52** [comment]
well ig i cant use it then since im using an old modpack, and if it gets updated i wouldent be able to use it anyways, so... is there any other way to make it work?

**Comment by CaitlynMainer** [comment]
Ask Mojang / Microsoft to reinstate the API very nicely?

**Comment by LittleTimmy52** [comment]
well... ok i cant use it, thanks anyways

**Comment by ben-mkiv** [comment]
i guess this is what fails 
https://github.com/PC-Logix/OpenSecurity/blob/1.12.2/src/main/java/pcl/opensecurity/common/tileentity/TileEntitySecurityTerminal.java#L116

`FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerProfileCache().getGameProfileForUsername()`

@LittleTimmy52 please try with the UUID, you can use https://mcuuid.net/ to figure out the UUID for any player name.
Use the result from the field `Full UUID`

**Comment by LittleTimmy52** [comment]
Well I'll try that once i get my mod pack working again

**Comment by LittleTimmy52** [comment]
@ben-mkiv 
![Capture](https://user-images.githubusercontent.com/90333044/195738827-1f16453d-acff-462d-90ef-fe541c9eb191.PNG)
after a long time i finally got my server up, but this is the result from terminal = require("component").os_securityterminal followed by terminal.adduser([password], "996336420b8f4429be368f8e64135526")

sorry for the long wait for a response

**Comment by ben-mkiv** [comment]
you have to use the full unique id with dashes

**Comment by LittleTimmy52** [comment]
> you have to use the full unique id with dashes

I did that too, same results

**Comment by ben-mkiv** [comment]
the command is `addUser`, not `adduser` things like this are case sensitive

**Comment by LittleTimmy52** [comment]
oh well when my mod pack is done taking a billion years to load ill try it

**Comment by LittleTimmy52** [comment]
ok, so it says user added, i go to check allowed users with the command and i get an error saying that the uuid is invalid. so i cant really tell if it worked seeing as the command getAllowedUsers broke and said uuid is invalid

**Comment by LittleTimmy52** [comment]
@ben-mkiv ive tried fiddeling more and i still have the exact same error when trying to see allowed users, invalid UUID string, do you know what else could be wrong?

**Comment by ben-mkiv** [comment]
yea the UUID parser seems to be faulty... i've fixed the code, but can't make a build of opensecurity right now, in the next update at least the UUID check should work

**Comment by LittleTimmy52** [comment]
> yea the UUID parser seems to be faulty... i've fixed the code, but can't make a build of opensecurity right now, in the next update at least the UUID check should work

Well looks like I'm stuck with it then (i can't edit mods in mod packs on aternos) whatever, atleast we tried

**Comment by ben-mkiv** [comment]
There's an alpha version on CurseForge now where the UUID check should work, but couldn't test it on my own yet.
https://www.curseforge.com/minecraft/mc-mods/opensecurity/files/4069429

**Comment by ben-mkiv** [comment]
feel free to open a new bug report if you still have problems with the new UUID check
