### ISSUE TITLE
[WIKI] Missing documentation for MagReader Doors.

### ISSUE THREAD

**Issue by ghost** [PC-Logix/OpenSecurity#177]
The wiki seems to be missing documentation for MagReader doors, or its extremetly hard to find.

Note: I am a new, my current assumpiton is that MagReader doors include a Mag Reader.

**Comment by ben-mkiv** [comment]
from what i know they act like Security Door + Magnetic Card Reader, while only the lower part of the door can be clicked with a mag card.

**Comment by cadergator10** [comment]
Hello. To my knowledge, a mag reader door is pretty much a door that can work as a magreader. I believe putting down magreader doors shows up as only a magreader, so all wiki information relating to magreaders should be the same.

**Comment by ben-mkiv** [comment]
feel free to open a new issue, if this wasn't solved...
