### ISSUE TITLE
Security Door issue

### ISSUE THREAD

**Issue by egorchik007** [PC-Logix/OpenSecurity#20]
It drops when destroyin as Iron Door.
Even a usual player can destroy it if he hits the upper part. 
Useless now :(

**Comment by CaitlynMainer** [comment]
Fixed in https://github.com/PC-Logix/OpenSecurity/commit/efec1511d5bc1a61b1ef12c043660abd31623664

**Comment by CaitlynMainer** [comment]
Also, https://github.com/PC-Logix/OpenSecurity/commit/f5505e1639ecc6f76cc7a3109bf166b71e9706b0 will back port this fix to existing doors
