### ISSUE TITLE
Crash upon loading Minecraft

### ISSUE THREAD

**Issue by Techokami** [PC-Logix/OpenSecurity#25]
OpenSecurity causes a NPE when registering its recipes with the latest build on Curseforge: http://paste.ee/p/TyQjU

**Comment by CaitlynMainer** [comment]
This is because of https://github.com/MightyPirates/OpenComputers/commit/12a37cf83a2dac43a4a4b07645e870684344a5cf

**Comment by Techokami** [comment]
No, 1.5.15 isn't released yet, but I like to stay fresh with OC on my server.
