### ISSUE TITLE
Security Breaks

### ISSUE THREAD

**Issue by alfw** [PC-Logix/OpenSecurity#27]
Hello, i was doing some testing with this mod today and come over some bad security breaks of the mod.

Frist problem i run into was that if you have a door placed. If you then rotate a piston to it and activate the piston to push the door, it will break and drop the door itself. Then you can just break the piston and go into the room.

Secound problem i come over was that a door controller  can be placed in front and behind the door. This allow a player to come with he's own door controller place it in front of the door, and open it for a own program. Then break down he's own computer and bypass the security door. Allow the door controller to only be placed on top, bottom or side where the player normal dont go will fix that problem. Or allow the set password to apply to the door itself when you run the setPassword from the first controller and check the passwor with the door and open it.

**Comment by CaitlynMainer** [comment]
Both of these will be fixed in build 59 when it's approved on curse

**Comment by alfw** [comment]
Tnx! :)

**Comment by alfw** [comment]
@CaitlynMainer The password protection on the door did not work. I did place down one door controller and a door. Used a computer to set a password on it. Then i placed a other one in front of the door and i was allowed to trigger only =component.os_door.toggle() and the door opened.

**Comment by alfw** [comment]
https://files.alfw.tv/1439038541-Alf-1244.mp4 | if you wonder what im doing.

**Comment by CaitlynMainer** [comment]
61 completely redoes how passwords are handled, and also requires the door controller placer match the door placer, which should resolve most issues.

**Comment by alfw** [comment]
@CaitlynMainer tnx for responding this quick to the stuff i find ;)
