### ISSUE TITLE
[Feature Request] Garage Doors/Shutters

### ISSUE THREAD

**Issue by cloakable** [PC-Logix/OpenSecurity#28]
Completely optional, but it would be nice to be able to secure say a 3x3 opening with a door. Like the Carpenters Blocks Garage Door or the one from Malisis Doors.

**Comment by CaitlynMainer** [comment]
While I'd love to do this, I have no idea where to start...  IF this was to happen it would have to be a while, my current job takes pretty much all of my free time.

**Comment by CaitlynMainer** [comment]
Great news! 3 years later this is getting done.

**Comment by SuPeRMiNoR2** [comment]
Better late then never!

**Comment by CaitlynMainer** [comment]
See 1.12.2 Build 20
