### ISSUE TITLE
Suggestion: Security Turret

### ISSUE THREAD

**Issue by Racerman2001** [PC-Logix/OpenSecurity#3]
Create a security turret similar to the Gun Turret from ICBM.  Allow players to create custom programs for the turret using Lua.  Also include pre-installed programs, such as scanning a certain radius, targeting a certain mob, etc.

**Comment by CaitlynMainer** [comment]
This will be a while in the future, as it requires stuff I have no idea how to do.

**Comment by MaHuJa** [comment]
See also https://github.com/OpenModularTurretsTeam/OpenModularTurrets
