### ISSUE TITLE
Energy Turret Won't fire

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [PC-Logix/OpenSecurity#33]
Energy turret refuses to fire. I tried with different numbers in the print(fire()). It moves to the spot, but refuses to actually shoot the bolt.
Energy turret has 2 damage upgrades
Mods list: http://pastebin.com/rfbNMVPp
Program and output: http://pastebin.com/UfbxYkav

**Comment by MajorGeneralRelativity** [comment]
I also tried it without the upgrades, and with a different turret

**Comment by CaitlynMainer** [comment]
I'm not able to reproduce this locally in dev, or in a built copy

**Comment by CaitlynMainer** [comment]
Was able to reproduce this on dedicated server only, will try to figure out why.
