### ISSUE TITLE
Off-thread invocation from Opencomputers

### ISSUE THREAD

**Issue by mzx987** [PC-Logix/OpenSecurity#34]
I understand that the error I am presenting you is mainly Fastcraft's fault, but it does this when I use the RFID Reader Block's "read()" function.
http://pastebin.com/TELzM2rq

I also decided to post it here because I don't know any better way to contact the creator of Fastcraft. But if this is something I need to contact him about, please let me know.

**Comment by CaitlynMainer** [comment]
The fastcraft thread on the IC2 forums seems to be the best/only way to contact play RE: Fastcraft.
http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820
AFAIK there is no way for me to fix this on my end, it's a side effect of how Fastcraft works.

**Comment by CaitlynMainer** [comment]
Thanks @fnuecke for pointing out the issue for me and saving me the better part of my next day off.
