### ISSUE TITLE
Keypad

### ISSUE THREAD

**Issue by AterIgnis** [PC-Logix/OpenSecurity#36]
Keypad block recipe is pretty much the same as numpads in OpenComputers and so i can not craft OC keyboards. Maybe use that in crafting instead of stone buttons

Also it would be good for some keypad feedback (one-line display for few characters (ex. 8) to show something like "DENIED" on incrorrect password, showing code being input or stars to at least let know how many characters are input. This feedback would be managed on computer side, so method like 'setText' and optionally 'setTextColor' would be enough for this. That's how my gpu+screen-based software-only keypads look like to this moment)

**Comment by CaitlynMainer** [comment]
Oh man.. I didn't even think about the recipe, it was copied directly from the source mod, I'll fix it later today.  As far as adding a display to the keypad, that's not likely to happen any time soon. I'm not totally ruling it out, but it's a huge pain.

**Comment by AterIgnis** [comment]
No problem with displays, they can be worked around by some external ones at the moment.
And as for recipe i guess something like OC numpad and some chips/transistors and maybe anything else would be good enough.

**Comment by CaitlynMainer** [comment]
Closes #36 
TIT
INI
ICI
T= Transistor
I=Iron
N=Number Pad
C=T1 Microchip

**Comment by Shuudoushi** [comment]
@CaitlynMainer just add a red and green 'led', that should satisfy the request.

**Comment by CaitlynMainer** [comment]
Still a pain, as it occupies 2 more meta entries unless I can figure out the TESR rendering textures..

**Comment by AterIgnis** [comment]
Forked this for myself and made keypad with 8 char feedback (with 3bit color, 1bit per channel) and even changeable button labels. May share if anyone interested.

**Comment by CaitlynMainer** [comment]
Would you care to contribute this back to the mod..?

**Comment by SuPeRMiNoR2** [comment]
what an idea!

**Comment by AterIgnis** [comment]
I'll get to contributing this after work, some things have to be polished and overall changes has to be merged.

Also i had some fun with turret, adding upsidedown placement and variable rotor length (so the gun can extend to neighboring block both visually and firing point-wise, but not collision, ex. turret going out of ceiling to shoot at intruders), those changes have to be separated before i can share any of them.

**Comment by CaitlynMainer** [comment]
Thanks, and I understand about work, I'm home for lunch atm.  I've been toying with upside down turret placement, so if you can get that working it'd be awesome as well.  Thanks!

**Comment by AterIgnis** [comment]
IDK if it is a good idea to propose Pull Request or not. I may missed some changed file or changed something i should not (as my own local dev version is stripped of nearly half blocks and some other stuff unused by me).
Would someone please check my repository branches and try to merge them locally?

[Turret](https://github.com/AterIgnis/OpenSecurity/tree/dev_turret)
[Keypad](https://github.com/AterIgnis/OpenSecurity/tree/dev_keypad)

Feel free to contact me in case of any questions or issues.

**Comment by CaitlynMainer** [comment]
Thanks @AterIgnis I've merged both of your improvements into OS!

**Comment by SuPeRMiNoR2** [comment]
That keypad looks awesome!

**Comment by AterIgnis** [comment]
You are welcome ^,..,^
