### ISSUE TITLE
Rendering Issue as of Build 88 causing Keypad to be darkened.

### ISSUE THREAD

**Issue by MyNameIsKodos** [PC-Logix/OpenSecurity#37]
Here is the keypad in my world as of Build 87:

![Build 87](http://i.imgur.com/HbZpsyp.png)

And here it is again, as of Build 88:

![Build 88](http://i.imgur.com/Vy2QKwk.png)

This wouldn't be a huge inconvenience, except that A) I have a hard enough time seeing, and B) keys can be colored, but aren't fullbright on my screen thus showing up as dark dark versions of the colors.

**Comment by CaitlynMainer** [comment]
Seems my fix didn't fix it... just reversed when it was an issue, more work tonight.
