### ISSUE TITLE
[Bug] Turret shoots in wrong direction. Turn bug?

### ISSUE THREAD

**Issue by McSharidan** [PC-Logix/OpenSecurity#38]
Build 88:
turret.moveTo(323 , 15)
Turret points upwards in posted direction. Shots however are dispensed in a completely different direction. In this case the shot goes off in a 90 degree offset angle and downwards, not up as expected.
Comparing between build 87 and 88, the turret in build 88 turns in the opposite direction of what it does it 87, thus invalidating any angle calculations made prior to build 88.

Something got messed up with the code handling turret / shot turning in build 88.

**Comment by CaitlynMainer** [comment]
@AterIgnis I think this has something to do with the changes I merged in from your fork as build 88's only changes are from there.  Any insight?

**Comment by AterIgnis** [comment]
I'll check turret with moveto(323,15) later today. Any additional information on reproducing the bug would be great.

**Comment by McSharidan** [comment]
uhm, well it's not that difficult reproducing the problem. Use the .moveTo() method to set any yaw and pitch you'd like and the have the turret fire shots. That's pretty much it. You'll notice that the turret points in one direction (90 degrees offset and in opposite direction of what build 87 does) and the shots go off in an entirely different direction (probably what they did in build 87).

It becomes more noticable if you change the pitch to some non-zero value. Turret points up, shots go down. Turret points down, shots go up.

**Comment by CaitlynMainer** [comment]
I'm wondering if I missed a file in my manual merge.. if so smack me..

**Comment by AterIgnis** [comment]
Aww, looks like i forgot to commit entity file...
That should fix firing wrong up/down. As for angles - if turn direction is reversed - it would not be hard to change too.

In my dev env i used some simple code to aim at sheeps with computronics radar to get target direction, but i had not compared with previous version, as commiting back was not my priority

**Comment by AterIgnis** [comment]
So, I've got a new commit: https://github.com/AterIgnis/OpenSecurity/commit/96641890ea04f6611365de50d0bdd0fe73f525fb

There EntityEnergyBolt.java should fix bolt mirrored flying up-down.

Other two files are for enabling old angles (should be 'old' by default).
TileEntityEnergyTurret.java:517 has constant '0', it should be changed to 90/-90 if turret is rotated by such constant from what it was before all my interventions.

**Comment by CaitlynMainer** [comment]
Thanks @AterIgnis I'll commit these and test.
