### ISSUE TITLE
if off internet

### ISSUE THREAD

**Issue by SvEgiiVEteR** [PC-Logix/OpenSecurity#39]
http://paste.ubuntu.com/14984285/
crash the client if off internet
if off internet
and always downloads the file klaxon2.ogg

**Comment by CaitlynMainer** [comment]
I'm looking into this issue, my current plan is to just ship the sounds ,and unpack them on run instead of downloading them.. it's proving to be more of a pain than I thought though.

**Comment by CaitlynMainer** [comment]
Fixed in build 91 will be on CurseForge soon
