### ISSUE TITLE
Instant destruction of door blocks

### ISSUE THREAD

**Issue by Programmdude** [PC-Logix/OpenSecurity#40]
Harvesting the door controller and security door works when you are using a pickaxe and are the owner, but when you are the owner and hit either of the blocks (left click) it will instantly destroy the block without dropping the item.

My recommendation for a solution would be to change the two blocks properties so they can be harvested by anything.

**Comment by JustPingo** [comment]
Also happens when you're not the owner. This is a major issue.

**Comment by CaitlynMainer** [comment]
@JustPingo Please provide evidence of instant destruction of blocks when not owner, I did identify the ability to break them, but I timed it and it took 1 minute and 18 seconds... That issue has been fixed though.

**Comment by JustPingo** [comment]
Well we just tested that on a server with a friend.
But I just noticed your brand new commit which probably fixes it, if the event wasn't cancelled.
Although you are setting the door block class' hardness to 0 if the owner of one of the tile entities wants to destroy it. But that impacts every other blocks. Do you, at some point restore it? I couldn't find any evidence of that.
Also, I don't believe setting the hardness to 0 is a good idea as you can instantly break it with your punch and don't get the block back.

**Comment by CaitlynMainer** [comment]
You still need to use a pick to break the blocks (The material is set to iron)  But Resistance is set to 4 and Hardness 6 for owners, and resets.

**Comment by JustPingo** [comment]
Yeah that's what I meant, as the tool is a multiplier, it will still be instant and loose the block.
Thanks for your fixes!
