### ISSUE TITLE
[BUG] Unable to load dependencies

### ISSUE THREAD

**Issue by spannerman79** [PC-Logix/OpenSecurity#5]
Forge 1448
Latest mods from chickenbones
[OpenSecurity-0.1.0-27](http://minecraft.curseforge.com/mc-mods/231687-opensecurity/files/2243095)

Server instances has no issues starting - just thought you might want to see any possible issues later on down the road so to speak
http://hastebin.com/esekuhoram.avrasm

**Comment by CaitlynMainer** [comment]
I'm going to need to see a full fml log, or atleast a full list of installed mods.

**Comment by CaitlynMainer** [comment]
Due to lack of feedback, I'm going to close this issue.  Please comment again if this is still a problem.
