### ISSUE TITLE
[Feature Request] Implantable RFID

### ISSUE THREAD

**Issue by MrabEzreb** [PC-Logix/OpenSecurity#50]
I think I also asked this of immibis peripherals (similar mod), but seriously, this would be the COOLEST THING :D
I tried to make a standalone mod for this a while back, but I don't have enough motivation to stick to anything for more than an hour, otherwise I would make a PR.

**Comment by CaitlynMainer** [comment]
This is already a thing, right click an entity/player with an RFID and it will "Implant" on them, you can then read that tag with either RFID Reader.

**Comment by MrabEzreb** [comment]
oh wow, installing this mod right now then :D
Is it possible to implant yourself?

**Comment by CaitlynMainer** [comment]
Umm... put it in a robot and have it "use" the RFID on you?  I'm not sure if that would work, other than that, no.

**Comment by MrabEzreb** [comment]
k
