### ISSUE TITLE
Component bug

### ISSUE THREAD

**Issue by gamecraft45** [PC-Logix/OpenSecurity#51]
In lua command
component.os_rfidreader.scan(10)
works but in program not.
![image](https://cloud.githubusercontent.com/assets/7279856/14589783/be52b42c-04ea-11e6-93f4-1014dd7082f1.png)

![image](https://cloud.githubusercontent.com/assets/7279856/14589785/dc132500-04ea-11e6-87aa-364d116071f0.png)

![image](https://cloud.githubusercontent.com/assets/7279856/14589779/8b6b53b6-04ea-11e6-811b-4d36bff10f78.png)

**Comment by MyNameIsKodos** [comment]
This is not a bug. You need to require component in your program.  Example:

```Lua
local component = require("component")

local data = component.os_rfidreader.scan(10)
```

Then you just need to process the 'data' as you wish further in the program

**Comment by CaitlynMainer** [comment]
Thanks @MyNameIsKodos
