### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by 31trainman** [PC-Logix/OpenSecurity#52]
I'm seeing this put in my console http://pastebin.com/RP1PQtFi

forge 1614
java 8 update 91
mac os x 10.11.4

mods list
AdvancedSolarPanel-1.7.10-3.5.1
  ATG-1.7.10-0.12.0
  AMT_Generators-1.7.10-1.4.2
  AOBD-2.9.1
  AOBDBB-1.0.6
  AppleMilkTea2-1.7.10_2.9k
  appliedenergistics2-rv3-beta-5
  AsieLib-1.7.10-0.4.5
  BetterFps-1.0.1
  BiblioCraft[v1.11.4][MC1.7.10]
  BiblioWoods[Forestry][v1.7]
  BiblioWoods[Natura][v1.5]
  BigDoors-1.7.10-1.1.0
  BigReactors-0.4.3A
  BiomesOPlenty-1.7.10-2.1.0.1889-universal
  buildcraft-7.1.16
  BuildcraftAdditions-1.7.10-2.2.5
  buildcraft-compat-7.1.4
  Carpenter's Blocks v3.3.8_dev_r8 - MC 1.7.10
  Chisel2-2.5.1.44
  ChiselTones-1.7.10-1.0-3
  ClimateControl-0.5.beta53
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.2-325
  ComputerCraft1.75
  Computronics-1.7.10-1.6.0
  DragonAPI 1.7.10 V12e
  Enchiridion 2-1.7.10-2.0.2a
  EnderIO-1.7.10-2.3.0.424_beta
  EnderZoo-1.7.10-1.0.15.32
  EnderCore-1.7.10-0.2.0.31_beta
  Eureka-1.7.10-3.0.2
  ExtraCells-1.7.10-2.3.9b188
  extrautilities-1.2.12
  ExtraTiC-1.7.10-1.4.5
  Farseek-1.0.11
  fastcraft-1.21
  Flaxbeard'sSteamPower-1.7.10-0.28.12
  FlenixCitiesCore_[1.7.10]-0.16.1-b122
  FlenixCitiesFood_[1.7.10]-0.5
  FlenixCitiesResearch_[1.7.10]-0.4
  FlenixRoads_[1.7.10]-0.9.0
  forestry_1.7.10-4.2.10.58
  FrameCompanion-1.1
  GardenStuff-1.7.10-1.7.0
  gasesFramework-1.7.10-1.2.0
  gases-1.7.10-1.6.3
  Guide-API-1.7.10-1.0.1-29
  ImmersiveEngineering-0.7.4
  immersiveintegration-0.6.7
  IGW-Mod-1.7.10-1.1.12-34-universal
  industrialcraft-2-2.2.817-experimental
  InventoryTweaks-1.59-dev-152
  IvToolkit-1.2
  JAFFA-1.72.13
  logisticspipes-0.9.3.121
  ModularPowersuits-0.11.0.300
  magneticraft-0.6.1-final
  malisisdoors-1.7.10-1.13.2
  malisisadvert-1.7.10-0.5.0
  malisiscore-1.7.10-0.14.3
  Mantle-1.7.10-0.3.2b
  Mariculture-Deluxe-1.7.10-1.2.4.2a
  mcjtylib-1.8.1
  Mekanism-1.7.10-8.1.9.265
  MekanismGenerators-1.7.10-8.1.9.265
  MekanismTools-1.7.10-8.1.9.265
  Metallurgy-1.7.10-4.0.8.97
  MetallurgyCore-1.7.10-4.0.4.18
  Minechem-1.7.10-5.0.5.406
  MineFactoryReloaded-[1.7.10]2.8.2B1-177
  natura-1.7.10-2.2.1a2
  neiaddons-1.12.15.41-mc1.7.10
  NEIIntegration-MC1.7.10-1.1.2
  NotEnoughResources-1.7.10-0.1.0-122
  NotEnoughIDs-1.4.2
  NotEnoughItems-1.7.10-1.0.5.118-universal
  IC2NuclearControl-2.3.4a
  Numina-0.4.0.131
  OpenBlocks-1.7.10-1.5.1
  OpenComputers-MC1.7.10-1.6.0.1-beta.1-universal
  OpenModsLib-1.7.10-0.9.1
  OpenPeripheral-1.7.10-AIO-7
  OpenSecurity-1.7.10-1.0-91
  Pam's HarvestCraft 1.7.10Lb
  PlanetguyLib-1.9.1
  ProjectBlue-1.1.6-mc1.7.10
  ProjectRed-1.7.10-4.7.0pre12.95-Compat
  ProjectRed-1.7.10-4.7.0pre12.95-Base
  ProjectRed-1.7.10-4.7.0pre12.95-World
  ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
  ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  ProjectRed-1.7.10-4.7.0pre12.95-Integration
  QuantumFlux-1.7.10-1.3.4
  Railcraft_1.7.10-9.9.0.0
  ReactorCraft 1.7.10 V12d
  RTG-1.7.10-0.7.0
  RemainInMotion-2.8.9
  rftools-4.23
  RotaryCraft 1.7.10 V12e
  sgu-bettergeo-1.7.10-1.2
  Streams-0.2
  ThermalDynamics-[1.7.10]1.1.0-161
  ThermalExpansion-[1.7.10]4.1.2-240
  ThermalFoundation-[1.7.10]1.2.3-112
  ThermalRecycling-1.7.10-1.1.0.5
  TiCTooltips-mc1.7.10-1.2.5
  TConstruct-1.7.10-1.8.8
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.10-1.1.6
  WarpDrive-1.7.10-1.3.21.-
  WR-CBE-1.7.10-1.4.1.9-universal
  YeGamolChattels-1.1.2
  zettaindustries-1.1-106
  Zora no Densha_v0.8_snapshot_Nov2015_MC 1.7.10
  Ztones-1.7.10-2.2.1

**Comment by CaitlynMainer** [comment]
Please test with latest build at http://ci.pc-logix.com/job/OpenSecurity-Dev/
