### ISSUE TITLE
Add device that allows protecting an area as long as it's active

### ISSUE THREAD

**Issue by Forecaster** [PC-Logix/OpenSecurity#53]
Something similar to the PneumaticCraft Security Station which while active prevents block placing, breaking and interacting from unauthorized players within a radius (up to 16 blocks per station).

Securing doors isn't super useful unless you can keep people from digging around them.

I wouldn't include the interact protection in this case of course.

**Comment by CaitlynMainer** [comment]
This is something I will look into..
