### ISSUE TITLE
Bug: If Developers website unavailable, both client and server fail to start

### ISSUE THREAD

**Issue by DraksterAU** [PC-Logix/OpenSecurity#54]
Hi Caitlyn,

The dependency checker in Open Security stops the server and / or client it is installed on from starting if your website is unavailable.

This includes if the .ogg files are already on the local machine as your mod seems to clear them with each client/server start.

I've removed the .info file that mentions these from the jar we're using but this probably needs to be addressed and pushed into an official release sometime :)

Regards,
DraksterAU

**Comment by CaitlynMainer** [comment]
The latest versions don't check the website for anything anymore.
