### ISSUE TITLE
Turret orientation input in Radians

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [PC-Logix/OpenSecurity#55]
Have either another method, or convert the current one to allow the inputting of Energy turret angle in Radians, because Radians are the way mathematicians do it, and the math.asin, math.acos, etc. output in radians. Degrees * 180 / (pi) = radians

**Comment by gamax92** [comment]
math.deg is a thing, it converts radians into degrees.

**Comment by MajorGeneralRelativity** [comment]
I know, but I wanted to avoid the overhead of calling it

**Comment by SuPeRMiNoR2** [comment]
If it was added to the mod, the mod would probably have to do the same conversion. So there really is no point.

**Comment by MajorGeneralRelativity** [comment]
I would like it, and radians are the more mathematical thing to do. Mimiru said to create an issue for it, so I did. If it doesn't happen, it doesn't.

**Comment by SuPeRMiNoR2** [comment]
Oh, sorry. In that case, I guess it will get added eventually XD

**Comment by MajorGeneralRelativity** [comment]
@SuPeRMiNoR2 you don't need to apologize. Your concerns are just as valid as my wishes :)

**Comment by CaitlynMainer** [comment]
Please test the latest dev build 47 and see if this works the way you'd like

**Comment by CaitlynMainer** [comment]
http://ci.pc-logix.com/job/OpenSecurity-Dev/
