### ISSUE TITLE
Turret error

### ISSUE THREAD

**Issue by MrLalatg** [PC-Logix/OpenSecurity#56]
if i type
turret = component.os_energyturret
turret.fire()
i got error 
![2016-08-26_12 51 02](https://cloud.githubusercontent.com/assets/21085285/18001466/c2ca5246-6b8b-11e6-9342-366e9c87a828.png)

**Comment by CaitlynMainer** [comment]
Turn it on. turret.powerOn()

**Comment by CaitlynMainer** [comment]
Also, call extendShaft(2) arm(true) to head off your next questions

**Comment by MrLalatg** [comment]
thx
