### ISSUE TITLE
2 turrets

### ISSUE THREAD

**Issue by MrLalatg** [PC-Logix/OpenSecurity#57]
if i have 2 turrets what ineed to write here
turret1=component.os_energyturret
turret2=????????
plz help

**Comment by CaitlynMainer** [comment]
Like all OpenComputers components, if you have more then one you have to get them by their UUID. turret1 = component.proxy(component.get("FIRST4TO5CHARSOFUUID")) turret2 = component.proxy(component.get("FIRST4TO5CHARSOFUUID"))  you can find the UUIDs by running the "components" command on the computer

**Comment by MrLalatg** [comment]
thx

**Comment by MrLalatg** [comment]
sry
how can i do automatic leveling ?

**Comment by CaitlynMainer** [comment]
automatic leveling..?

**Comment by MrLalatg** [comment]
sorry my english is very bad
for automatic shoot moving players or entities

**Comment by CaitlynMainer** [comment]
Ah, you don't.  You'll have to track entities yourself via the Entity Detector, or OC's Motion Sensor. the turrets do not have any built in tracking.
