### ISSUE TITLE
EntityDetector

### ISSUE THREAD

**Issue by MrLalatg** [PC-Logix/OpenSecurity#59]
my friend stands infront entity detector but when i write
entity.scanPlayers()
i got this
![2016-08-26_19 28 13](https://cloud.githubusercontent.com/assets/21085285/18012656/32d46914-6bc3-11e6-95cd-4b10de6a2201.png)
![2016-08-26_19 28 13](https://cloud.githubusercontent.com/assets/21085285/18012657/33a933b0-6bc3-11e6-8f28-05828acec1c8.png)

**Comment by CaitlynMainer** [comment]
It's a table.. you don't print tables directly.  https://www.lua.org/pil/2.5.html
