### ISSUE TITLE
Turret coords

### ISSUE THREAD

**Issue by MrLalatg** [PC-Logix/OpenSecurity#60]
how can i move turret to coords(x,y) because turret.moveTo() is not for cords

**Comment by CaitlynMainer** [comment]
What do you mean it's not for coords?  Are you trying to move the turret to a different block location?  moveTo is for aiming the turret in degrees, like moveTo(90,0) will turn the turret to 90deg and aim it level.

**Comment by MrLalatg** [comment]
if i want to aim someone or something which stays at coords -1211 45 how can i do this?

**Comment by LizzyTrickster** [comment]
you'd need to use math to work out where that block is in relation to the turret and then rotate to face it
