### ISSUE TITLE
No sounds list on alarm.listSounds()

### ISSUE THREAD

**Issue by As2piK** [PC-Logix/OpenSecurity#62]
Hello,

I'm trying to use alarms from OpenSecurity. Unfortunatly, it seems no sounds are available for alarms, as I do a alarm.listSounds(), it return an empty table.

Are they missing from the server, or it's a plugin problem ?

Here's my code, I also may failed in it ! http://puu.sh/rpMMZ/f6a858dd19.png

Thank you :)

**Comment by CaitlynMainer** [comment]
What version of the mod are you on? Also does /mods/opensecurity/sounds/alarms/ have anything in it?

**Comment by As2piK** [comment]
We are using 1.0.94, and I don't have access right now to server files, I'm asking to the admin :)

edit : in my local game files the folder is empty, so that's comes from here ?

**Comment by CaitlynMainer** [comment]
Could you see if this works in SP?  Also, you'll need to make sure _you_ have the alarms as well, so check your /mods/opensecurity/alarms directory too

**Comment by As2piK** [comment]
ok so I guess files are missing on our modpack. I'll ask to our admin to add them :) Thanks for the quick answers ! :D

**Comment by CaitlynMainer** [comment]
They're supposed to auto extract when you start the game, if they aren't I'm going to need more info.
OS: Windows/OSX/Linux, Java version,  and log files.

**Comment by As2piK** [comment]
We are using a custom private modpack for biggest french Minecraft Youtubers (#FeedThePatrick on Twitter ;)), so I'll ask to our server admin and I'll come back to you.

Thank you !

**Comment by Azenet** [comment]
Pack admin here, `/mods/opensecurity/sounds/alarms` is created but empty. No logs were found, neither `Extracting file:` nor `Can't detect valid JAR`, but the files are there in the JAR file. This is using different Windows versions with Java 8 and Forge 10.13.4.1614.

**Comment by CaitlynMainer** [comment]
._. how is this failing again suddenly?!  Thanks I'll look into this.

**Comment by CaitlynMainer** [comment]
Please try build 53 from http://ci.pc-logix.com/job/OpenSecurity-Dev/ thanks!

**Comment by CaitlynMainer** [comment]
Any update on this @Azenet or @As2piK ?

**Comment by CaitlynMainer** [comment]
Closing this for lack of feedback, in my testing it works on Windows Clients and Server, as well as Linux,  I don't have an osx based device to test on.  This change will be in the latest stable soon.

**Comment by Azenet** [comment]
Sorry, haven't had time to try it out yet, but since the issue was Windows-related it should work fine for us as well. I'll report when I can push the update.
