### ISSUE TITLE
Port to 1.8+

### ISSUE THREAD

**Issue by CaitlynMainer** [PC-Logix/OpenSecurity#63]
Heya @AterIgnis since you were the original author of the Turrets, I was wondering if you had any 1.8+ modding experience and if so if you'd be interested in helping me port at least the turrets to 1.8 and beyond.  Thanks!

**Comment by AterIgnis** [comment]
Sorry, I had no such experience, my modding for MC is mostly based around fixing issues and crashes in mods which I get for my server... And either there I rarely recompile them, instead making some small bytecode patches if possible.

**Comment by CaitlynMainer** [comment]
Alrighty thanks anyway!
