### ISSUE TITLE
Update to 1.10.2

### ISSUE THREAD

**Issue by ghost** [PC-Logix/OpenSecurity#64]
OpenComputers is update to 1.10.2, and my server is updated, too.
But I need this mod, because it's very useful.

**Comment by CaitlynMainer** [comment]
Oh... my comment didn't post.. good to know.

I replied that there is a 1.10.2 port in the works, but so much changed from 1.7 to 1.10 that it's basically a rewrite and it's going very slow.

**Comment by ghost** [comment]
@CaitlynMainer When will it be finished?

**Comment by MyNameIsKodos** [comment]
It will be done when it's done. Asking for an ETA does nothing positive for anyone.
