### ISSUE TITLE
Can someone explain, how does one simply adds new alarms sounds?

### ISSUE THREAD

**Issue by Technus** [PC-Logix/OpenSecurity#66]
I am on build 94, tried putting the ogg files in:

- /mods/opensecurity/sounds/alarms
- /mods/OpenSecurity/sounds/alarms

**Comment by CaitlynMainer** [comment]
Just put the oggs in /mods/OpenSecurity/sounds/alarms  listSounds() is broken and doesn't show anything, but the added alarms DO work, note they have to be on the client AND server, as OS's list of playable sounds has to be the same on both.  I'll release a build with a fixed listSounds() soon.

**Comment by CaitlynMainer** [comment]
Build 95: http://michi.pc-logix.com/javaw_2016-11-06_09-16-22.png http://michi.pc-logix.com/javaw_2016-11-06_09-17-15.png

**Comment by Technus** [comment]
OC's list of playable sounds - first time i  hear that, could you expand, since iirc the config for playable sounds in alarm is non existent.

**Comment by SuPeRMiNoR2** [comment]
The point of that was that you need to have custom alarms on both the client and the server. I don't think OCs internal sound list is something you can interact with directly.

**Comment by CaitlynMainer** [comment]
OC is all server side. So when you try to play an alarm, OS checks if the alarm exists, which it can only do on the server.  If the alarms aren't on the client AND server, when the OC thread that runs the component request with OS on the server the alarm won't exist, and it can't play it.  There is no config for alarms anymore, it was replaced with a directory listing awhile ago, the only stipulation is, the alarms have to exist on ALL clients, and the server.

**Comment by Technus** [comment]
Thanks, i just assumed that the term means something else than the sync of files.

**Comment by CaitlynMainer** [comment]
Build 95 is on Curse now, so the issue should be fixed.
