### ISSUE TITLE
Problem with klaxon2.ogg

### ISSUE THREAD

**Issue by Panzergrenadier** [PC-Logix/OpenSecurity#67]
Problem with connection to http://caitlynmainer.com/OpenSecurity/klaxon2.ogg (404 error). Tryed puting this file in mods folder manualy, but it doesn't help. Why?

**Comment by CaitlynMainer** [comment]
This is a duplicate of #65 ALSO opened by you, and I told you what to do to fix it.   Update the mod!  Build #91 removed the need to download the resources from my site, I'm not supporting a build from almost a year ago.  Update. Go. Do it.  If you're using a mod pack you should have the pack creator update the mod, it's insanely out of date... Also, slap them for me.
