### ISSUE TITLE
Cannot have more then one door controller.

### ISSUE THREAD

**Issue by tndmadman** [PC-Logix/OpenSecurity#68]
So, iv been going at this for atleast 2 hours. thinking it was my bad coding skills. witch it might be. I have 2 car readers settup and 2 door controllers settup. They both controll double doors. When i did this with just one double door settup it worked fine. but when i tried to settup 2 even after selecting the ID of the 2 different door controllers it wont work.

Both card readers pick it up but only the first door controller i placed down works. So if i use ither card reader the first door will be effected. Coding problem or mod problem? help please 
Paste bin code is NeKhRW9Z thanks for any help in advance

**Comment by CaitlynMainer** [comment]
That's because OpenComputers uses the first component it finds as the "primary"  to work with multiples of the same component on a network you have to do like
`controller1 = component.proxy(component.get("first_few_uuid_chars"))

controller2 = component.proxy(component.get("first_few_uuid_chars_of_2nd_component"))`

Then you just do controller1.toggle() and controller2.toggle()

**Comment by tndmadman** [comment]
Ok thank you.

**Comment by tndmadman** [comment]
Ok so i gave this a try i cant get it to work....... it throws a proxy error so i thought it needed to require a proxy lib but thats not a thing idk
pastebin with proxy includded KbK4WbV1 http://imgur.com/a/Eb2pT
pastebin without. 4RHapwpY http://imgur.com/a/wQDFg

**Comment by Forecaster** [comment]
Please include proper Pastebin links...

Just putting the id is awful.

**Comment by SuPeRMiNoR2** [comment]
I would like to state first that this is not even an OpenSecurity issue, this is just Open Computers.
Secondly, does your actual code still have the lines
`controller1 = component.proxy(component.get("first_few_uuid_chars"))`
`controller2 = component.proxy(component.get("first_few_uuid_chars_of_2nd_component"))`

You need to put the actual first few characters of the component uuid there, not the words "first_few_uuid_chars" (Use the [Analyzer](http://ocdoc.cil.li/item:analyzer) from OC to get the UUID of a physical block)

You might also want to use the [OC Wiki](http://ocdoc.cil.li/component:component_access) to read about component access, and maybe Open Computers in general. There is quite a lot of good information on that wiki

Finally, these are not actual issues with OpenSecurity, so please do not keep commenting on this issue. If you need more help with Open Computers, use the OC [forums](https://oc.cil.li/index.php?/index) or the OC IRC Channel. (#oc on irc.esper.net)

**Comment by tndmadman** [comment]
ok thanks sorry for being a pain in the ass. im new to all of this lol
