### ISSUE TITLE
[Suggestion] Blast resistant server rack.

### ISSUE THREAD

**Issue by Shuudoushi** [PC-Logix/OpenSecurity#7]
Should be easy enough to implement, just take the vanilla OC server rack, make it a darker color, boost the blast resistances and done. For the recipe, 8 obsidian around a server rack should do.

After thought: The same treatment can be done to the regular computer cases as well.

**Comment by CaitlynMainer** [comment]
It seems I can't extend the OC Case class from java, per Sangar.

**Comment by ben-mkiv** [comment]
closing this as i've decided to add the feature to OCDevices (which has a custom rack which can be upgraded with blast resistance)

https://www.curseforge.com/minecraft/mc-mods/ocdevices
