### ISSUE TITLE
Alarm playing default sound.

### ISSUE THREAD

**Issue by Technus** [PC-Logix/OpenSecurity#70]
OpenSecurity-1.7.10-1.0-95

Alarms are present both on server and client, and listed when .listSounds() is called. Still the block plays the default sound?

a.setAlarm("alarm")
a.activate()
    //plays default on MP only
a.deactivate()
a.setAlarm("alarm.ogg")
a.activate()
    //playes default on SP and MP

**Comment by CaitlynMainer** [comment]
This is fixed in build #97 which will be approved on curse soon.  Do not include the ".ogg" in the alarm name.  The issue was "AlarmResource" is client side only and I was checking a map in that class to validate alarm selections.

**Comment by Technus** [comment]
TYVM
