### ISSUE TITLE
Keypad issue, low info about that!

### ISSUE THREAD

**Issue by Gamerexde** [PC-Logix/OpenSecurity#71]
Hi, i was trying of how to use the keypad, but there is low information about events and that, can some one help me and tell me, oh and add more info regarding events to keypad.

**Comment by CaitlynMainer** [comment]
https://github.com/PC-Logix/OpenSecurity/wiki/Blocks#keypad

the default event is "keypad"  you'll get a keypad event for every button press, with the button index, and the button label, if you're not sure how to use it, run dmesg on the computer, and press some buttons.

**Comment by Gamerexde** [comment]
No, what i mean is when i try to get that value on variable like print(keypad) that is the issue, can you pleas tell me that, only display the number that i type on the KeyPad.

**Comment by Angelnightwing** [comment]
This is a question better asked on the forums, rather than an issue tracker.

**Comment by Gamerexde** [comment]
:(

**Comment by CaitlynMainer** [comment]
print(keypad) isn't going to work... you'll have to setup an event listener, or do ``_,_, button, button_label = event.pull("keypad")`` then print button or button_label

**Comment by Gamerexde** [comment]
Sorry, im very nuub for this, can you make an example? xd

**Comment by CaitlynMainer** [comment]
https://oc.cil.li/index.php?/forum/31-programming/

**Comment by Gamerexde** [comment]
Oh ok done! xd
