### ISSUE TITLE
Crash on startup (NullPointerException)

### ISSUE THREAD

**Issue by ReTeYeZ** [PC-Logix/OpenSecurity#74]
Crash report [here.](https://pastebin.com/BipCLZNg)

**Comment by CaitlynMainer** [comment]
Hmm, that means the coremod didn't run to unpack the assets...  Matter of fact the coremod isn't even registered o_O  Thanks I'll look into this.

**Comment by CaitlynMainer** [comment]
Please try this build: http://ci.pc-logix.com/job/OpenSecurity%201.10/12/artifact/build/libs/OpenSecurity-MC1.10.2-1.0-12.jar

**Comment by ReTeYeZ** [comment]
This one works, thanks.
