### ISSUE TITLE
[1.10.2-1.0-18] - The Alarm block is not playing sounds.

### ISSUE THREAD

**Issue by crosenquist** [PC-Logix/OpenSecurity#76]
A basic redstone current is having no impact on the Alarm block.

I've tested 1.0-12 and 1.0-18, and they are broken in both versions as far as I can tell. Also, I've not seen any changelogs or users reporting this since the 1.10.2 upgrade so I'm not sure if you are aware of this or not.

**Comment by CaitlynMainer** [comment]
Redstone hasn't worked on alarms in a very long time.

But thanks to me misreading your report, I did find out that the node wasn't being created for the alarm component, which I've fixed.

**Comment by crosenquist** [comment]
Awesome!

With the node issue fixed, will the block now begin producing sound when used with OpenComputers?

**Comment by CaitlynMainer** [comment]
yeah, you'll call activate()/deactivate() as before.
