### ISSUE TITLE
[1.10.2] Inventory display issue when viewing Card Writer

### ISSUE THREAD

**Issue by mzx987** [PC-Logix/OpenSecurity#77]
I've noticed that, for some strange reason, my inventory is shifted over by one (except for the hotbar) when right-clicking and viewing the Card Writer. The top left will be replaced when shifting, and the bottom right will be replaced with something from the bottom-most armor slot.

Below is a link showing images before and after:
https://imgur.com/a/gXu6E

Is this an issue with this mod, or a conflict with another one?

**Comment by CaitlynMainer** [comment]
Is this only a display issue? Like if you close the card writer GUI your actual inventory is unchanged?

**Comment by CaitlynMainer** [comment]
Also, can you try the GUI for the Turret? to see if it does the same thing.

**Comment by mzx987** [comment]
It's just a display issue. After getting out of the GUI and looking back into my inventory, nothing actually moved. Sorry for not clarifying that earlier.

Right-clicking the Energy Turret doesn't affect my inventory.

**Comment by CaitlynMainer** [comment]
sounds like I have an off-by-one index in the card writer, thanks I'll investigate.

**Comment by mzx987** [comment]
Not a problem. Thanks for the quick response!

**Comment by CaitlynMainer** [comment]
This should be fixed in build 22 on CurseForge as soon as it is approved.
