### ISSUE TITLE
Need assistance with coding a magnetic card, or some other card.

### ISSUE THREAD

**Issue by Stryder914** [PC-Logix/OpenSecurity#78]
I'm not the best at coding, so, asking you would be a big embarrassment to have admitted to it. Could you mind helping me out with setting some of the machines up? The wiki page didn't help me that much

**Comment by CaitlynMainer** [comment]
The code here: https://github.com/PC-Logix/OpenSecurity/wiki/Blocks#card-writer is literally all there is to it.   This is the card writer program I include with the mod https://git.io/vHoiY  as you can see, the highlighted line there is all the "important" part of it.  everything else just prompts for data and stores it to be used on that line.

**Comment by Stryder914** [comment]
That's exactly what I said wasn't helping me, i typed them in, they didn't do anything.

**Comment by CaitlynMainer** [comment]
That is *literally* all there is to it.
local component = require("component")
local writer = component.os_cardwriter
writer.write("data","title",false)

This http://michi.pc-logix.com/javaw_2017-06-06_20-39-01.png
makes this http://michi.pc-logix.com/javaw_2017-06-06_20-39-29.png

Which, if you READ the code on either page, is pretty much *exactly* that.

**Comment by Stryder914** [comment]
Okay...
