### ISSUE TITLE
Can't no craft open security disk 

### ISSUE THREAD

**Issue by craig1988** [PC-Logix/OpenSecurity#79]
Will not work in crafting table ?

**Comment by CaitlynMainer** [comment]
1.7, or 1.10? if 1.10 that's because SecureOS doesn't work on newer OC versions so it's not craftable.

**Comment by craig1988** [comment]
1.10.2

**Comment by craig1988** [comment]
Is there any kind of control program out anything I can download at all really want to get this working there is a release for 1.10.2 tho so what doesn't it work ?

**Comment by craig1988** [comment]
Is there anyway for me to use the systems at all its a great mod I'm just not great with lua coding

**Comment by CaitlynMainer** [comment]
SecureOS wasn't a "control program"  it's a fork of OpenOS with a bit more security.  There isn't really a "control program" for OpenSecurity, you can check the OpenComputers forums I've seen some programs that do door control and mag/rfid readers.

**Comment by craig1988** [comment]
How do I acutely interface with the turret and other items tho what are the commands ?

**Comment by craig1988** [comment]
I tried to download one of paste bin I downloaded it to autorun.lue but having trouble executing it

**Comment by craig1988** [comment]
Basically just asking how to install once it down loaded

**Comment by craig1988** [comment]
Your help in this would be so appreciated

**Comment by craig1988** [comment]
Please lol

Sent from my iPhone

**Comment by craig1988** [comment]
Your not going to help me are you lol

**Comment by CaitlynMainer** [comment]
First off, quit spamming the issue tracker.
Second off, post your programming questions here: https://oc.cil.li/index.php?/forum/31-programming/ or use IRC/Discord irc.esper.net and join #oc , or https://webchat.esper.net/ and join #oc
