### ISSUE TITLE
[Feature Request][1.10.2] Functions to change lights on Magnetic Card Reader

### ISSUE THREAD

**Issue by mzx987** [PC-Logix/OpenSecurity#82]
Not sure if this is already implemented, but it would be neat to have control over the lights on the front of the Card Reader to give the player a sense of status for the card they swiped.

**Comment by CaitlynMainer** [comment]
This IS a feature in the 1.7.10 version, I've not ported it to 1.10 yet

**Comment by mzx987** [comment]
Alrighty. I kind of forgot that it was already a feature in 1.7.10.
