### ISSUE TITLE
Conflict with the alarm in SecurityCraft

### ISSUE THREAD

**Issue by Geforce132** [PC-Logix/OpenSecurity#83]
Hey there, fellow modder!

One of your TileEntities is being registered with the same name as one of mine, specifically the "alarm", which causes a crash. Any way that you could possibly change it, or want me to change mine?

**Comment by CaitlynMainer** [comment]
Oh.. I forgot to prefix my TEs..  umm... will changing the TE name cause dataloss?

**Comment by Geforce132** [comment]
I believe so.... any NBT data stored in alarms already placed down might be lost, I think?
