### ISSUE TITLE
Door Controller FPS Issue

### ISSUE THREAD

**Issue by tndmadman** [PC-Logix/OpenSecurity#84]
App on adding these to my base. I started to notice that my fps was going down... Ignore it
I got 8 of them latter before i realized that my fps was 10... Normally, i get 100-120
So i started taking everything down tell i got to these, then it went back up
1 of theses drops me down to 30fps anf 2 to 20.. ect. 
Im not sure why but it needs looked into.
The modpack its in is Space Astronamy

**Comment by CaitlynMainer** [comment]
http://michi.pc-logix.com/javaw_2017-07-09_21-20-21.png 57 FPS with all of those down, mind you I'm also running FFXIV which is impacting my FPS.

**Comment by tndmadman** [comment]
I dont know why but on there public server it does it but not in single
player...

**Comment by CaitlynMainer** [comment]
I can't reproduce this on my mod pack on my server either.

Is this a 1.7, or 1.10 pack..?

**Comment by tndmadman** [comment]
Strange, must be a modpack issue. thanks for looking into it ill have the
modpack author look into it

**Comment by CaitlynMainer** [comment]
I have identified a possible issue in the 1.7.10 version that *could* cause issues on already overloaded servers, I'll try to implement a fix this weekend to use code more like the 1.10.2 version.  I still can't reproduce this, but my server is pretty empty too..

**Comment by tndmadman** [comment]
thank you for looking into it, yea that server has alot of people on it,
mostly 10-12 people when im on

**Comment by CaitlynMainer** [comment]
Would it be possible to give this a shot? http://ci.pc-logix.com/job/OpenSecurity-Dev/79/artifact/build/libs/OpenSecurity-1.7.10-1.0-79.jar  I'm not near a computer able to run MC right now, so I can't even test if this works.. so tossing it into Single Player first might be a good idea.
