### ISSUE TITLE
[1.10.2] Crash with SecurityCraft

### ISSUE THREAD

**Issue by mzx987** [PC-Logix/OpenSecurity#87]
Seems a little odd (since I've never encountered an error like this before), but this mod and SecurityCraft share the same ID titled "alarm".

Here is the crash report: https://pastebin.com/1E9DWvX4

I also sent a crash report to them as well.

**EDIT:** I uh... Didn't realize that an issue like this was closed 5 days ago. Sorry if this is a duplicate issue...

**Comment by CaitlynMainer** [comment]
yeah, this has been fixed, just not released.
