### ISSUE TITLE
Request - Port to 1.12.1

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PC-Logix/OpenSecurity#88]
Hey I could use some awesome security care to help? I understand if your busy or still learning 1.12.1 code just wondering.

**Comment by Martmists-GH** [comment]
There's an in-development branch for 1.12, but it seems to not have anything ported as of now. I'd help her out if I knew what had to be done and how, but sadly I don't :(

**Comment by CaitlynMainer** [comment]
Ported to 1.12.2
