### ISSUE TITLE
Need Help With KeyPad and MagStrip Reader

### ISSUE THREAD

**Issue by EmmaTheDevTDGZ** [PC-Logix/OpenSecurity#89]
Hello I was wondering if you could help me with the MagStrip reader and Keypad

**Comment by EmmaTheDevTDGZ** [comment]
sorry my username changed its cdbrunow

**Comment by MyNameIsKodos** [comment]
What do you need help with?

**Comment by EmmaTheDevTDGZ** [comment]
coding it

**Comment by EmmaTheDevTDGZ** [comment]
I am new to coding with open computers

**Comment by EmmaTheDevTDGZ** [comment]
and some help with door controller

**Comment by EmmaTheDevTDGZ** [comment]
the wiki is out of date

**Comment by MyNameIsKodos** [comment]
Well, this is my template program for the keypad:
```Lua
-- User Variables

local pin = 1234 -- Change this to whatever you want the PIN to be. No more than 8 chars

-- Requires

local component = require("component")
local event = require("event")
local os = require("os")
local computer = require("computer")

-- Hardware

local kp = component.os_keypad


-- Misc

local char_space = string.byte(" ")
local running = true
local currButton = ""


-- Keypad init

kpButtons = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "CLR", "0", "ENT"}
kpColors = {15, 15, 15, 15, 15, 15, 15, 15, 15, 12, 15, 10}
kp.setKey(kpButtons, kpColors)

---

function display(text,color)
kp.setDisplay(text,color)
os.sleep(.5)
kp.setDisplay("", 15)
end

function unknownEvent()
end

local myEventHandlers = setmetatable({}, { __index = function() return unknownEvent end})

function myEventHandlers.key_up(adress, char, code, playerName)
  if (char == char_space) then
    running = false
  end
end

function myEventHandlers.keypad(address, id, buttonLabel)
if (id == 10) then
  currButton = ""
  kp.setDisplay("", 15)
else if (id == 12) then
  if (currButton == tostring(pin)) then
    currButton = ""
    display("GRANTED", 10)
    -- Do stuff here if the entered code is right
  else
    currButton = ""
    display("DENIED", 12)
    -- Do stuff here if the code is wrong
  end
else
  currButton = currButton .. buttonLabel
  kp.setDisplay(currButton, 15)
end
end
end

function handleEvent(eventID, ...)
  if (eventID) then 
    myEventHandlers[eventID](...)
  end
end

while running do
 handleEvent(event.pull())
end
```

To use the magnetic card reader, you'll first need to use the included program, os_cardwriter (iirc), to write data to a card. Then just use dmesg.lua to check the event that runs when the card is swiped to use the data received by the reader.

**Comment by CaitlynMainer** [comment]
There.. the wiki is no longer "out of date" the only thing different about the door controller was that it was renamed from os_door to os_doorcontroller, which 10 seconds of looking at the output of `components` would have shown.  @MyNameIsKodos's script there is a very good example of how to use the components.

**Comment by EmmaTheDevTDGZ** [comment]
thank you

**Comment by EmmaTheDevTDGZ** [comment]
Could some one put @MyNameIsKodos script on paste bin so I could download it. Thank you.

**Comment by CaitlynMainer** [comment]
Is there a reason you can't put it on pastebin?  Just copy it from here, open pastebin.com click new paste, paste it, save it, then get the paste id...

**Comment by EmmaTheDevTDGZ** [comment]
Ok thanks

**Comment by MyNameIsKodos** [comment]
Should also be noted that you can just run `wget https://raw.githubusercontent.com/MyNameIsKodos/OpenComputers-Programs/master/misc/kp_test.lua` and get it that way, too
