### ISSUE TITLE
[Feature Request] Data Card in  Block form

### ISSUE THREAD

**Issue by Kodos-Atoz** [PC-Logix/OpenSecurity#9]
The OC Data Card is great, but it currently only exists in card form, which uses one of a limited number of slots.  I'd like to formally request that there be a block version in OS so that I can use card slots for other things.

**Comment by CaitlynMainer** [comment]
This isn't going to be a carbon copy of the data card, but I will make sure to implement the same methods and returns while adding my own touches.
