### ISSUE TITLE
Speed of an energy bolt

### ISSUE THREAD

**Issue by neumannfe** [PC-Logix/OpenSecurity#90]
So i want to make a program which calculates the position of an entity when a turret would hit it but i do not have the speed an energy bold would have. are there differences between the shaftlegh of 1 and the shaftlengh 2? please answer..

**Comment by CaitlynMainer** [comment]
The speed of the energy bolt *should* be about the same as an arrow, 1.5f, IDK what that equates to in m/s and shaft length is just for looks if I remember correctly, it's been a while since I worked on energy turrets.

**Comment by neumannfe** [comment]
Thanks
