### ISSUE TITLE
Security Door plays 'Eerie Sound' when opening/closing.

### ISSUE THREAD

**Issue by IKnowBashFu** [PC-Logix/OpenSecurity#91]
Tested on a SpongeForge server in 1.10.2. Sounds like your typical cave sound when opening/closing.

Will update with test results from single-player.

**Comment by CaitlynMainer** [comment]
I can't reproduce this in SP, or a Vanilla MP server.

**Comment by IKnowBashFu** [comment]
Maybe I'm missing something. Vanilla MP server? Do you mean Forge server? Is it possible to connect with mods to a vanilla server? Either way, just tested on Forge server, version forge-1.10.2-12.18.3.2477, and it's playing the eerie sound. Could this be something on their end?

**Comment by CaitlynMainer** [comment]
Sorry I meant Vanilla forge.

**Comment by IKnowBashFu** [comment]
Running only OpenComputers and OpenSecurity build 31, on forge-1.10.2-12.18.3.2477, with no other mods, I'm still getting eerie noise playing when opening security doors. Which version of forge did you test on your end with?

Edit: this is on a multiplayer forge server. The singleplayer has no issue, same version.

**Comment by CaitlynMainer** [comment]
Seems it was a change in a later version of forge.. I'm not sure what I was on, but I upgraded and it started happening.  The fix was pretty stupid, I just switched sounds to the system I had implemented but never used. *sighs*
