### ISSUE TITLE
General Help Needed

### ISSUE THREAD

**Issue by tomtechweb** [PC-Logix/OpenSecurity#95]
Hi,

I think the wiki needs more information to make it easier for New users. There aren’t any good tutorials that I have found yet for making a simple door lock. I also think you should make some pieces of code that run ‘out of the box’ so players can see how the mod works - there should be different complexity levels: A multi-user permission based server-client system, A multi-door system, a simple all-in-one system etc.

Thanks,
Tom

**Comment by CaitlynMainer** [comment]
I don't know Lua well enough to do that in anyway that would be the slightest bit helpful to anyone new.

**Comment by tomq0608** [comment]
I’d really appreciate a demo (multi-door, client-Server) because idk how to use it and I just want an easy solution

**Comment by SuPeRMiNoR2** [comment]
You could look at this, it is a door control program that lets you control multiple doors from one computer, and add and remove mag cards to a list of authorized cards. I am not sure if it works on the newest version of Minecraft but I know it still works in 1.7.10. https://github.com/OpenPrograms/SuPeRMiNoR2-Programs/tree/master/osmagdoor
