### ISSUE TITLE
Feature Request/Question:

### ISSUE THREAD

**Issue by LawsOfScience** [PC-Logix/OpenSecurity#97]
So, I’ve noticed that Security Doors break when you remove the block under them (like a normal door). I think that they shouldn’t do this because they’re not called Security Doors for a reason. 
The question part of this is: Can Security Doors be broken by someone other than the person that placed them? If so, that should be fixed as well.

Sorry if I’ve wasted your time.

**Comment by CaitlynMainer** [comment]
Sorry I forgot to answer the question.  The door can only be broken by the placer of the door, or by an OP.
